//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildStep) DeepCopyInto(out *BuildStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildStep.
func (in *BuildStep) DeepCopy() *BuildStep {
	if in == nil {
		return nil
	}
	out := new(BuildStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUPinningSpec) DeepCopyInto(out *CPUPinningSpec) {
	*out = *in
	if in.SiblingPairing != nil {
		in, out := &in.SiblingPairing, &out.SiblingPairing
		*out = new(bool)
		**out = **in
	}
	if in.LaunchRtPriority != nil {
		in, out := &in.LaunchRtPriority, &out.LaunchRtPriority
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUPinningSpec.
func (in *CPUPinningSpec) DeepCopy() *CPUPinningSpec {
	if in == nil {
		return nil
	}
	out := new(CPUPinningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromRevisionSource) DeepCopyInto(out *FromRevisionSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromRevisionSource.
func (in *FromRevisionSource) DeepCopy() *FromRevisionSource {
	if in == nil {
		return nil
	}
	out := new(FromRevisionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromSandboxSource) DeepCopyInto(out *FromSandboxSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromSandboxSource.
func (in *FromSandboxSource) DeepCopy() *FromSandboxSource {
	if in == nil {
		return nil
	}
	out := new(FromSandboxSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSVolumeSource) DeepCopyInto(out *GCSVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSVolumeSource.
func (in *GCSVolumeSource) DeepCopy() *GCSVolumeSource {
	if in == nil {
		return nil
	}
	out := new(GCSVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUResources) DeepCopyInto(out *GPUResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUResources.
func (in *GPUResources) DeepCopy() *GPUResources {
	if in == nil {
		return nil
	}
	out := new(GPUResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOutput) DeepCopyInto(out *GitOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOutput.
func (in *GitOutput) DeepCopy() *GitOutput {
	if in == nil {
		return nil
	}
	out := new(GitOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitPushRecord) DeepCopyInto(out *GitPushRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitPushRecord.
func (in *GitPushRecord) DeepCopy() *GitPushRecord {
	if in == nil {
		return nil
	}
	out := new(GitPushRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitVolumeSource) DeepCopyInto(out *GitVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitVolumeSource.
func (in *GitVolumeSource) DeepCopy() *GitVolumeSource {
	if in == nil {
		return nil
	}
	out := new(GitVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicy) DeepCopyInto(out *NetworkPolicy) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowCIDRs != nil {
		in, out := &in.AllowCIDRs, &out.AllowCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InboundCIDRs != nil {
		in, out := &in.InboundCIDRs, &out.InboundCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy.
func (in *NetworkPolicy) DeepCopy() *NetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnTerminate) DeepCopyInto(out *OnTerminate) {
	*out = *in
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]OutputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnTerminate.
func (in *OnTerminate) DeepCopy() *OnTerminate {
	if in == nil {
		return nil
	}
	out := new(OnTerminate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputSpec) DeepCopyInto(out *OutputSpec) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitOutput)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputSpec.
func (in *OutputSpec) DeepCopy() *OutputSpec {
	if in == nil {
		return nil
	}
	out := new(OutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCVolumeSource) DeepCopyInto(out *PVCVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCVolumeSource.
func (in *PVCVolumeSource) DeepCopy() *PVCVolumeSource {
	if in == nil {
		return nil
	}
	out := new(PVCVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolPlacement) DeepCopyInto(out *PoolPlacement) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolPlacement.
func (in *PoolPlacement) DeepCopy() *PoolPlacement {
	if in == nil {
		return nil
	}
	out := new(PoolPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSnapshotRefresh) DeepCopyInto(out *PoolSnapshotRefresh) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSnapshotRefresh.
func (in *PoolSnapshotRefresh) DeepCopy() *PoolSnapshotRefresh {
	if in == nil {
		return nil
	}
	out := new(PoolSnapshotRefresh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSnapshots) DeepCopyInto(out *PoolSnapshots) {
	*out = *in
	if in.SnapshotDelay != nil {
		in, out := &in.SnapshotDelay, &out.SnapshotDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Refresh != nil {
		in, out := &in.Refresh, &out.Refresh
		*out = new(PoolSnapshotRefresh)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSnapshots.
func (in *PoolSnapshots) DeepCopy() *PoolSnapshots {
	if in == nil {
		return nil
	}
	out := new(PoolSnapshots)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolTemplateSpec) DeepCopyInto(out *PoolTemplateSpec) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BuildSteps != nil {
		in, out := &in.BuildSteps, &out.BuildSteps
		*out = make([]BuildStep, len(*in))
		copy(*out, *in)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]SandboxVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultBudget != nil {
		in, out := &in.DefaultBudget, &out.DefaultBudget
		*out = new(SandboxBudget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolTemplateSpec.
func (in *PoolTemplateSpec) DeepCopy() *PoolTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PoolTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolWarm) DeepCopyInto(out *PoolWarm) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolWarm.
func (in *PoolWarm) DeepCopy() *PoolWarm {
	if in == nil {
		return nil
	}
	out := new(PoolWarm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionDiffSummary) DeepCopyInto(out *RevisionDiffSummary) {
	*out = *in
	if in.Added != nil {
		in, out := &in.Added, &out.Added
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Removed != nil {
		in, out := &in.Removed, &out.Removed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionDiffSummary.
func (in *RevisionDiffSummary) DeepCopy() *RevisionDiffSummary {
	if in == nil {
		return nil
	}
	out := new(RevisionDiffSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionSource) DeepCopyInto(out *RevisionSource) {
	*out = *in
	if in.FromWorkspaceRevision != nil {
		in, out := &in.FromWorkspaceRevision, &out.FromWorkspaceRevision
		*out = new(WorkspaceRevisionRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionSource.
func (in *RevisionSource) DeepCopy() *RevisionSource {
	if in == nil {
		return nil
	}
	out := new(RevisionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3VolumeSource) DeepCopyInto(out *S3VolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3VolumeSource.
func (in *S3VolumeSource) DeepCopy() *S3VolumeSource {
	if in == nil {
		return nil
	}
	out := new(S3VolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sandbox) DeepCopyInto(out *Sandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sandbox.
func (in *Sandbox) DeepCopy() *Sandbox {
	if in == nil {
		return nil
	}
	out := new(Sandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Sandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxBudget) DeepCopyInto(out *SandboxBudget) {
	*out = *in
	if in.MaxForks != nil {
		in, out := &in.MaxForks, &out.MaxForks
		*out = new(int32)
		**out = **in
	}
	if in.MaxCheckpoints != nil {
		in, out := &in.MaxCheckpoints, &out.MaxCheckpoints
		*out = new(int32)
		**out = **in
	}
	if in.MaxCpuSeconds != nil {
		in, out := &in.MaxCpuSeconds, &out.MaxCpuSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaxLifetimeExtension != nil {
		in, out := &in.MaxLifetimeExtension, &out.MaxLifetimeExtension
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxEgressBytes != nil {
		in, out := &in.MaxEgressBytes, &out.MaxEgressBytes
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxBudget.
func (in *SandboxBudget) DeepCopy() *SandboxBudget {
	if in == nil {
		return nil
	}
	out := new(SandboxBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxBudgetSpend) DeepCopyInto(out *SandboxBudgetSpend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxBudgetSpend.
func (in *SandboxBudgetSpend) DeepCopy() *SandboxBudgetSpend {
	if in == nil {
		return nil
	}
	out := new(SandboxBudgetSpend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxChild) DeepCopyInto(out *SandboxChild) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxChild.
func (in *SandboxChild) DeepCopy() *SandboxChild {
	if in == nil {
		return nil
	}
	out := new(SandboxChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxExpose) DeepCopyInto(out *SandboxExpose) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedPrincipals != nil {
		in, out := &in.AllowedPrincipals, &out.AllowedPrincipals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedEmailDomains != nil {
		in, out := &in.AllowedEmailDomains, &out.AllowedEmailDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxExpose.
func (in *SandboxExpose) DeepCopy() *SandboxExpose {
	if in == nil {
		return nil
	}
	out := new(SandboxExpose)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxLifetime) DeepCopyInto(out *SandboxLifetime) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.OnTerminate != nil {
		in, out := &in.OnTerminate, &out.OnTerminate
		*out = new(OnTerminate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxLifetime.
func (in *SandboxLifetime) DeepCopy() *SandboxLifetime {
	if in == nil {
		return nil
	}
	out := new(SandboxLifetime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxList) DeepCopyInto(out *SandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sandbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxList.
func (in *SandboxList) DeepCopy() *SandboxList {
	if in == nil {
		return nil
	}
	out := new(SandboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxNetwork) DeepCopyInto(out *SandboxNetwork) {
	*out = *in
	if in.ExtraAllow != nil {
		in, out := &in.ExtraAllow, &out.ExtraAllow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxNetwork.
func (in *SandboxNetwork) DeepCopy() *SandboxNetwork {
	if in == nil {
		return nil
	}
	out := new(SandboxNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPool) DeepCopyInto(out *SandboxPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPool.
func (in *SandboxPool) DeepCopy() *SandboxPool {
	if in == nil {
		return nil
	}
	out := new(SandboxPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPoolList) DeepCopyInto(out *SandboxPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPoolList.
func (in *SandboxPoolList) DeepCopy() *SandboxPoolList {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPoolSpec) DeepCopyInto(out *SandboxPoolSpec) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(PoolTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = new(PoolSnapshots)
		(*in).DeepCopyInto(*out)
	}
	if in.Warm != nil {
		in, out := &in.Warm, &out.Warm
		*out = new(PoolWarm)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PoolPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUPinning != nil {
		in, out := &in.CPUPinning, &out.CPUPinning
		*out = new(CPUPinningSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPoolSpec.
func (in *SandboxPoolSpec) DeepCopy() *SandboxPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPoolStatus) DeepCopyInto(out *SandboxPoolStatus) {
	*out = *in
	if in.LastSnapshotTime != nil {
		in, out := &in.LastSnapshotTime, &out.LastSnapshotTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeDistribution != nil {
		in, out := &in.NodeDistribution, &out.NodeDistribution
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastScaleDownTime != nil {
		in, out := &in.LastScaleDownTime, &out.LastScaleDownTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPoolStatus.
func (in *SandboxPoolStatus) DeepCopy() *SandboxPoolStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxResources) DeepCopyInto(out *SandboxResources) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(GPUResources)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxResources.
func (in *SandboxResources) DeepCopy() *SandboxResources {
	if in == nil {
		return nil
	}
	out := new(SandboxResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSource) DeepCopyInto(out *SandboxSource) {
	*out = *in
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.FromSandbox != nil {
		in, out := &in.FromSandbox, &out.FromSandbox
		*out = new(FromSandboxSource)
		**out = **in
	}
	if in.FromRevision != nil {
		in, out := &in.FromRevision, &out.FromRevision
		*out = new(FromRevisionSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSource.
func (in *SandboxSource) DeepCopy() *SandboxSource {
	if in == nil {
		return nil
	}
	out := new(SandboxSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSpec) DeepCopyInto(out *SandboxSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeOverrides != nil {
		in, out := &in.VolumeOverrides, &out.VolumeOverrides
		*out = make([]VolumeOverride, len(*in))
		copy(*out, *in)
	}
	if in.WorkspaceRef != nil {
		in, out := &in.WorkspaceRef, &out.WorkspaceRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(SandboxNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.Expose != nil {
		in, out := &in.Expose, &out.Expose
		*out = new(SandboxExpose)
		(*in).DeepCopyInto(*out)
	}
	if in.Budget != nil {
		in, out := &in.Budget, &out.Budget
		*out = new(SandboxBudget)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(SandboxLifetime)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSpec.
func (in *SandboxSpec) DeepCopy() *SandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxStatus) DeepCopyInto(out *SandboxStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.BudgetSpend != nil {
		in, out := &in.BudgetSpend, &out.BudgetSpend
		*out = new(SandboxBudgetSpend)
		**out = **in
	}
	if in.EffectiveBudget != nil {
		in, out := &in.EffectiveBudget, &out.EffectiveBudget
		*out = new(SandboxBudget)
		(*in).DeepCopyInto(*out)
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]SandboxChild, len(*in))
		copy(*out, *in)
	}
	if in.CheckpointTime != nil {
		in, out := &in.CheckpointTime, &out.CheckpointTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxStatus.
func (in *SandboxStatus) DeepCopy() *SandboxStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxVolume) DeepCopyInto(out *SandboxVolume) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(VolumeSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxVolume.
func (in *SandboxVolume) DeepCopy() *SandboxVolume {
	if in == nil {
		return nil
	}
	out := new(SandboxVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretMount) DeepCopyInto(out *SecretMount) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretMount.
func (in *SecretMount) DeepCopy() *SecretMount {
	if in == nil {
		return nil
	}
	out := new(SecretMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeOverride) DeepCopyInto(out *VolumeOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeOverride.
func (in *VolumeOverride) DeepCopy() *VolumeOverride {
	if in == nil {
		return nil
	}
	out := new(VolumeOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSource) DeepCopyInto(out *VolumeSource) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3VolumeSource)
		**out = **in
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(GCSVolumeSource)
		**out = **in
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCVolumeSource)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitVolumeSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSource.
func (in *VolumeSource) DeepCopy() *VolumeSource {
	if in == nil {
		return nil
	}
	out := new(VolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workspace) DeepCopyInto(out *Workspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workspace.
func (in *Workspace) DeepCopy() *Workspace {
	if in == nil {
		return nil
	}
	out := new(Workspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Workspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceGit) DeepCopyInto(out *WorkspaceGit) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceGit.
func (in *WorkspaceGit) DeepCopy() *WorkspaceGit {
	if in == nil {
		return nil
	}
	out := new(WorkspaceGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceGrant) DeepCopyInto(out *WorkspaceGrant) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceGrant.
func (in *WorkspaceGrant) DeepCopy() *WorkspaceGrant {
	if in == nil {
		return nil
	}
	out := new(WorkspaceGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceList) DeepCopyInto(out *WorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Workspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceList.
func (in *WorkspaceList) DeepCopy() *WorkspaceList {
	if in == nil {
		return nil
	}
	out := new(WorkspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRetention) DeepCopyInto(out *WorkspaceRetention) {
	*out = *in
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRetention.
func (in *WorkspaceRetention) DeepCopy() *WorkspaceRetention {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRevision) DeepCopyInto(out *WorkspaceRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRevision.
func (in *WorkspaceRevision) DeepCopy() *WorkspaceRevision {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRevisionList) DeepCopyInto(out *WorkspaceRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkspaceRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRevisionList.
func (in *WorkspaceRevisionList) DeepCopy() *WorkspaceRevisionList {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRevisionRef) DeepCopyInto(out *WorkspaceRevisionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRevisionRef.
func (in *WorkspaceRevisionRef) DeepCopy() *WorkspaceRevisionRef {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRevisionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRevisionSpec) DeepCopyInto(out *WorkspaceRevisionSpec) {
	*out = *in
	out.WorkspaceRef = in.WorkspaceRef
	in.Source.DeepCopyInto(&out.Source)
	if in.MemorySnapshotRef != nil {
		in, out := &in.MemorySnapshotRef, &out.MemorySnapshotRef
		*out = new(string)
		**out = **in
	}
	if in.MemorySnapshotPrincipal != nil {
		in, out := &in.MemorySnapshotPrincipal, &out.MemorySnapshotPrincipal
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRevisionSpec.
func (in *WorkspaceRevisionSpec) DeepCopy() *WorkspaceRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRevisionStatus) DeepCopyInto(out *WorkspaceRevisionStatus) {
	*out = *in
	if in.DiffSummary != nil {
		in, out := &in.DiffSummary, &out.DiffSummary
		*out = new(RevisionDiffSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.GitPushes != nil {
		in, out := &in.GitPushes, &out.GitPushes
		*out = make([]GitPushRecord, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRevisionStatus.
func (in *WorkspaceRevisionStatus) DeepCopy() *WorkspaceRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceS3Store) DeepCopyInto(out *WorkspaceS3Store) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceS3Store.
func (in *WorkspaceS3Store) DeepCopy() *WorkspaceS3Store {
	if in == nil {
		return nil
	}
	out := new(WorkspaceS3Store)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSpec) DeepCopyInto(out *WorkspaceSpec) {
	*out = *in
	in.Store.DeepCopyInto(&out.Store)
	in.Git.DeepCopyInto(&out.Git)
	in.Retention.DeepCopyInto(&out.Retention)
	if in.Grants != nil {
		in, out := &in.Grants, &out.Grants
		*out = make([]WorkspaceGrant, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSpec.
func (in *WorkspaceSpec) DeepCopy() *WorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceStatus) DeepCopyInto(out *WorkspaceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceStatus.
func (in *WorkspaceStatus) DeepCopy() *WorkspaceStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceStore) DeepCopyInto(out *WorkspaceStore) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(WorkspaceS3Store)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionKeyRef != nil {
		in, out := &in.EncryptionKeyRef, &out.EncryptionKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceStore.
func (in *WorkspaceStore) DeepCopy() *WorkspaceStore {
	if in == nil {
		return nil
	}
	out := new(WorkspaceStore)
	in.DeepCopyInto(out)
	return out
}
