// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/sandbox/controlv1/internal.proto

// Internal host-to-guest control service (sandbox.internal.v1).
//
// This service carries secrets and the fork-correctness handshake. It is served
// by the guest agent on a DISTINCT vsock service port from the public Sandbox
// service. It is NEVER part of sandbox.v1.Sandbox, NEVER exposed on forkd :9091,
// and NEVER reachable from tenant code. The host (forkd) is the only caller.
//
// All three RPCs may carry sensitive material:
//   - NotifyForked: Entropy is raw CRNG seed material; HostWallClockNanos can
//     leak host timing. Neither is ever logged by host or guest.
//   - Configure: Env and Secrets are claim-time secret values injected into the
//     guest process environment. Values are NEVER logged or echoed by either side.
//   - Ping: carries no secrets; used for health checks.
//
// Package is versioned independently of sandbox.v1 with a one-major-version
// compatibility window (docs/api/runtime-protocol.md). The service name
// "sandbox.internal.v1.Control" is the vsock service discriminator used by the
// guest to accept connections on its dedicated control port.

package sandboxinternalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StartWorkloadRequest declares the serving workload the build starts and
// snapshots while it is running (issue #460).
type StartWorkloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the serving process argv, run through the shell in the guest.
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// env are NON-secret environment variables for the workload. Secret values are
	// delivered per fork via Configure and never baked into the snapshot. Keys are
	// safe to log; values are not.
	Env map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// cwd is the working directory; empty means the guest default.
	Cwd string `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// ready, when set, is the HTTP gate the guest waits on before returning, so the
	// snapshot captures a listening app. Absent means snapshot as soon as started.
	Ready         *HttpReady `protobuf:"bytes,4,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkloadRequest) Reset() {
	*x = StartWorkloadRequest{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkloadRequest) ProtoMessage() {}

func (x *StartWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkloadRequest.ProtoReflect.Descriptor instead.
func (*StartWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkloadRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartWorkloadRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartWorkloadRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartWorkloadRequest) GetReady() *HttpReady {
	if x != nil {
		return x.Ready
	}
	return nil
}

// HttpReady is the in-guest HTTP readiness gate for a serving workload. All
// fields are plain values and safe to log.
type HttpReady struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port is the guest TCP port the workload listens on.
	Port uint32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// path is the request path; empty defaults to "/".
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// expect is the HTTP status that counts as ready; 0 defaults to 200.
	Expect uint32 `protobuf:"varint,3,opt,name=expect,proto3" json:"expect,omitempty"`
	// timeout_seconds bounds the readiness wait; 0 defaults to 120.
	TimeoutSeconds uint32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HttpReady) Reset() {
	*x = HttpReady{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpReady) ProtoMessage() {}

func (x *HttpReady) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpReady.ProtoReflect.Descriptor instead.
func (*HttpReady) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{1}
}

func (x *HttpReady) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HttpReady) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpReady) GetExpect() uint32 {
	if x != nil {
		return x.Expect
	}
	return 0
}

func (x *HttpReady) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// StartWorkloadResponse reports the started workload. Safe to log.
type StartWorkloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sid is the workload's session id, which the guest records so the per-fork
	// SIGUSR2 reset broadcast excludes the workload's session.
	Sid int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	// ready is true when the readiness gate passed, or when no gate was requested.
	Ready         bool `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkloadResponse) Reset() {
	*x = StartWorkloadResponse{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkloadResponse) ProtoMessage() {}

func (x *StartWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkloadResponse.ProtoReflect.Descriptor instead.
func (*StartWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{2}
}

func (x *StartWorkloadResponse) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *StartWorkloadResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// NotifyForkedRequest mirrors internal/vsock.NotifyForkedRequest field-for-field.
//
// Entropy and host_wall_clock_nanos are SENSITIVE: Entropy is raw CRNG seed
// material and the clock can leak host timing. Neither field is ever logged by
// host or guest; only applied-step magnitudes and reseed success are logged.
type NotifyForkedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// generation is the fork sequence number; the guest uses it to detect
	// replayed or out-of-order notifications.
	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// host_wall_clock_nanos is the host wall time at fork time, in nanoseconds
	// since the Unix epoch. The guest steps CLOCK_REALTIME to this value to
	// correct the clock drift introduced by snapshot/restore.
	// SENSITIVE: do not log.
	HostWallClockNanos int64 `protobuf:"varint,2,opt,name=host_wall_clock_nanos,json=hostWallClockNanos,proto3" json:"host_wall_clock_nanos,omitempty"`
	// entropy is fresh host CRNG output delivered to the guest so it can reseed
	// its kernel entropy pool after restore. Forks share the snapshot's entropy
	// state; without this injection every fork starts from the same seed.
	// SENSITIVE: do not log.
	Entropy []byte `protobuf:"bytes,3,opt,name=entropy,proto3" json:"entropy,omitempty"`
	// network, when set, carries this fork's per-fork network identity (distinct
	// guest IP, gateway, prefix, and optional MAC). The guest reconfigures eth0
	// on receipt. Fields are plain addresses and safe to log.
	Network *NotifyForkedNetwork `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	// volumes is the per-fork volume mount table. The host rebinds each backing
	// drive before sending this notification; the guest mounts each entry at its
	// designated path. Empty means no volumes. Device nodes and paths are safe
	// to log.
	Volumes       []*VolumeMountEntry `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyForkedRequest) Reset() {
	*x = NotifyForkedRequest{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyForkedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyForkedRequest) ProtoMessage() {}

func (x *NotifyForkedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyForkedRequest.ProtoReflect.Descriptor instead.
func (*NotifyForkedRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyForkedRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *NotifyForkedRequest) GetHostWallClockNanos() int64 {
	if x != nil {
		return x.HostWallClockNanos
	}
	return 0
}

func (x *NotifyForkedRequest) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

func (x *NotifyForkedRequest) GetNetwork() *NotifyForkedNetwork {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *NotifyForkedRequest) GetVolumes() []*VolumeMountEntry {
	if x != nil {
		return x.Volumes
	}
	return nil
}

// NotifyForkedNetwork mirrors internal/vsock.NotifyForkedNetwork field-for-field.
// All fields are plain network addresses and safe to log.
type NotifyForkedNetwork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// guest_ip is the IPv4 address assigned to eth0 in the guest (e.g.
	// "10.0.1.2").
	GuestIp string `protobuf:"bytes,1,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	// gateway_ip is the default route target, the host side of the per-fork /30
	// (e.g. "10.0.1.1").
	GatewayIp string `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	// prefix_len is the network prefix length (e.g. 30 for a /30).
	PrefixLen int32 `protobuf:"varint,3,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	// guest_mac, when non-empty, is this fork's distinct eth0 hardware address
	// (e.g. "02:ab:cd:ef:01:02"). The guest sets it before bringing the link up
	// so each fork has a distinct MAC. Empty leaves the snapshot-baked MAC in
	// place.
	GuestMac string `protobuf:"bytes,4,opt,name=guest_mac,json=guestMac,proto3" json:"guest_mac,omitempty"`
	// resolver_ip, when non-empty, is the DNS resolver the guest must use. The
	// guest writes it as the sole nameserver in /etc/resolv.conf. Empty leaves
	// resolv.conf untouched.
	ResolverIp string `protobuf:"bytes,5,opt,name=resolver_ip,json=resolverIp,proto3" json:"resolver_ip,omitempty"`
	// proxy_endpoint is the fork-stable HTTP(S) proxy address (host:port) the
	// guest egresses through. The guest agent exports it as HTTP_PROXY and
	// HTTPS_PROXY so egress is attributed and policy-enforced by the host proxy.
	// Empty means the per-sandbox egress proxy is disabled. Config, safe to log.
	ProxyEndpoint string `protobuf:"bytes,6,opt,name=proxy_endpoint,json=proxyEndpoint,proto3" json:"proxy_endpoint,omitempty"`
	// reset_upstreams tells the guest this is a live fork: drop stale route and
	// neighbor state after re-addressing eth0 so captured upstream sockets die
	// and clients re-dial through the proxy. False (the default) leaves existing
	// connections in place, which is correct for a cold fork from a snapshot.
	// Config, safe to log.
	ResetUpstreams bool `protobuf:"varint,7,opt,name=reset_upstreams,json=resetUpstreams,proto3" json:"reset_upstreams,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyForkedNetwork) Reset() {
	*x = NotifyForkedNetwork{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyForkedNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyForkedNetwork) ProtoMessage() {}

func (x *NotifyForkedNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyForkedNetwork.ProtoReflect.Descriptor instead.
func (*NotifyForkedNetwork) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyForkedNetwork) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *NotifyForkedNetwork) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *NotifyForkedNetwork) GetPrefixLen() int32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *NotifyForkedNetwork) GetGuestMac() string {
	if x != nil {
		return x.GuestMac
	}
	return ""
}

func (x *NotifyForkedNetwork) GetResolverIp() string {
	if x != nil {
		return x.ResolverIp
	}
	return ""
}

func (x *NotifyForkedNetwork) GetProxyEndpoint() string {
	if x != nil {
		return x.ProxyEndpoint
	}
	return ""
}

func (x *NotifyForkedNetwork) GetResetUpstreams() bool {
	if x != nil {
		return x.ResetUpstreams
	}
	return false
}

// VolumeMountEntry mirrors internal/vsock.VolumeMountEntry field-for-field.
// All fields are config values, not secrets, and safe to log.
type VolumeMountEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device is the guest block device node (e.g. "/dev/vdb") assigned by the
	// drive attach order (rootfs is /dev/vda; the i-th volume is /dev/vd{b+i}).
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// mount_path is where the guest mounts the device.
	MountPath string `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	// read_only attaches the device MS_RDONLY so a shared or read-only volume
	// cannot be modified by the guest.
	ReadOnly      bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMountEntry) Reset() {
	*x = VolumeMountEntry{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMountEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMountEntry) ProtoMessage() {}

func (x *VolumeMountEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMountEntry.ProtoReflect.Descriptor instead.
func (*VolumeMountEntry) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{5}
}

func (x *VolumeMountEntry) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *VolumeMountEntry) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *VolumeMountEntry) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// NotifyForkedResponse mirrors internal/vsock.NotifyForkedResponse field-for-field.
// All fields are observability counters and magnitudes, never raw secret values.
type NotifyForkedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// applied_clock_step_nanos is the signed adjustment applied to CLOCK_REALTIME
	// in nanoseconds (0 when drift was within the guest's tolerance threshold).
	AppliedClockStepNanos int64 `protobuf:"varint,1,opt,name=applied_clock_step_nanos,json=appliedClockStepNanos,proto3" json:"applied_clock_step_nanos,omitempty"`
	// reseeded_rng is true when at least one entropy-injection path into the
	// kernel pool succeeded.
	ReseededRng bool `protobuf:"varint,2,opt,name=reseeded_rng,json=reseededRng,proto3" json:"reseeded_rng,omitempty"`
	// signaled_processes is the count of userspace processes that received the
	// CRNG-reseed signal so they can reinitialize their own PRNGs.
	SignaledProcesses int32 `protobuf:"varint,3,opt,name=signaled_processes,json=signaledProcesses,proto3" json:"signaled_processes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotifyForkedResponse) Reset() {
	*x = NotifyForkedResponse{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyForkedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyForkedResponse) ProtoMessage() {}

func (x *NotifyForkedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyForkedResponse.ProtoReflect.Descriptor instead.
func (*NotifyForkedResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyForkedResponse) GetAppliedClockStepNanos() int64 {
	if x != nil {
		return x.AppliedClockStepNanos
	}
	return 0
}

func (x *NotifyForkedResponse) GetReseededRng() bool {
	if x != nil {
		return x.ReseededRng
	}
	return false
}

func (x *NotifyForkedResponse) GetSignaledProcesses() int32 {
	if x != nil {
		return x.SignaledProcesses
	}
	return 0
}

// ConfigureRequest mirrors internal/vsock.ConfigureRequest field-for-field.
//
// THIS MESSAGE CARRIES SECRET VALUES. env and secrets values are claim-time
// credentials injected into the guest process environment. Neither side ever
// logs values; only key names and entry counts are safe to log. This message
// must never appear on any public service or surface.
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// env is the set of environment variables to merge into the guest environment.
	// Values may be secret; log only keys and the entry count.
	Env map[string]string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// secrets is the set of secret values (e.g. API tokens, credentials) to
	// inject. Values are NEVER logged or echoed by either side.
	Secrets       map[string]string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ConfigureRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// ConfigureResponse acknowledges successful delivery of Configure. It carries
// no payload; success is indicated by the absence of an RPC error.
type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{8}
}

// PingRequest carries no fields; it is a struct so future knobs can be added
// without changing the wire tag.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{9}
}

// PingResponse mirrors internal/vsock.PingResponse field-for-field.
// Carries no secrets; safe to log.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uptime_seconds is the guest agent process uptime in fractional seconds,
	// matching the vsock protocol's float64 "uptime_seconds" JSON field.
	UptimeSeconds float64 `protobuf:"fixed64,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_sandbox_controlv1_internal_proto protoreflect.FileDescriptor

const file_proto_sandbox_controlv1_internal_proto_rawDesc = "" +
	"\n" +
	"&proto/sandbox/controlv1/internal.proto\x12\x13sandbox.internal.v1\"\xf6\x01\n" +
	"\x14StartWorkloadRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12D\n" +
	"\x03env\x18\x02 \x03(\v22.sandbox.internal.v1.StartWorkloadRequest.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x124\n" +
	"\x05ready\x18\x04 \x01(\v2\x1e.sandbox.internal.v1.HttpReadyR\x05ready\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\tHttpReady\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06expect\x18\x03 \x01(\rR\x06expect\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\"?\n" +
	"\x15StartWorkloadResponse\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x05R\x03sid\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\"\x87\x02\n" +
	"\x13NotifyForkedRequest\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x121\n" +
	"\x15host_wall_clock_nanos\x18\x02 \x01(\x03R\x12hostWallClockNanos\x12\x18\n" +
	"\aentropy\x18\x03 \x01(\fR\aentropy\x12B\n" +
	"\anetwork\x18\x04 \x01(\v2(.sandbox.internal.v1.NotifyForkedNetworkR\anetwork\x12?\n" +
	"\avolumes\x18\x05 \x03(\v2%.sandbox.internal.v1.VolumeMountEntryR\avolumes\"\xfc\x01\n" +
	"\x13NotifyForkedNetwork\x12\x19\n" +
	"\bguest_ip\x18\x01 \x01(\tR\aguestIp\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x02 \x01(\tR\tgatewayIp\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x03 \x01(\x05R\tprefixLen\x12\x1b\n" +
	"\tguest_mac\x18\x04 \x01(\tR\bguestMac\x12\x1f\n" +
	"\vresolver_ip\x18\x05 \x01(\tR\n" +
	"resolverIp\x12%\n" +
	"\x0eproxy_endpoint\x18\x06 \x01(\tR\rproxyEndpoint\x12'\n" +
	"\x0freset_upstreams\x18\a \x01(\bR\x0eresetUpstreams\"f\n" +
	"\x10VolumeMountEntry\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xa1\x01\n" +
	"\x14NotifyForkedResponse\x127\n" +
	"\x18applied_clock_step_nanos\x18\x01 \x01(\x03R\x15appliedClockStepNanos\x12!\n" +
	"\freseeded_rng\x18\x02 \x01(\bR\vreseededRng\x12-\n" +
	"\x12signaled_processes\x18\x03 \x01(\x05R\x11signaledProcesses\"\x96\x02\n" +
	"\x10ConfigureRequest\x12@\n" +
	"\x03env\x18\x01 \x03(\v2..sandbox.internal.v1.ConfigureRequest.EnvEntryR\x03env\x12L\n" +
	"\asecrets\x18\x02 \x03(\v22.sandbox.internal.v1.ConfigureRequest.SecretsEntryR\asecrets\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ConfigureResponse\"\r\n" +
	"\vPingRequest\"5\n" +
	"\fPingResponse\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x01R\ruptimeSeconds2\xff\x02\n" +
	"\aControl\x12c\n" +
	"\fNotifyForked\x12(.sandbox.internal.v1.NotifyForkedRequest\x1a).sandbox.internal.v1.NotifyForkedResponse\x12Z\n" +
	"\tConfigure\x12%.sandbox.internal.v1.ConfigureRequest\x1a&.sandbox.internal.v1.ConfigureResponse\x12K\n" +
	"\x04Ping\x12 .sandbox.internal.v1.PingRequest\x1a!.sandbox.internal.v1.PingResponse\x12f\n" +
	"\rStartWorkload\x12).sandbox.internal.v1.StartWorkloadRequest\x1a*.sandbox.internal.v1.StartWorkloadResponseB;Z9mitos.run/mitos/proto/sandbox/controlv1;sandboxinternalv1b\x06proto3"

var (
	file_proto_sandbox_controlv1_internal_proto_rawDescOnce sync.Once
	file_proto_sandbox_controlv1_internal_proto_rawDescData []byte
)

func file_proto_sandbox_controlv1_internal_proto_rawDescGZIP() []byte {
	file_proto_sandbox_controlv1_internal_proto_rawDescOnce.Do(func() {
		file_proto_sandbox_controlv1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sandbox_controlv1_internal_proto_rawDesc), len(file_proto_sandbox_controlv1_internal_proto_rawDesc)))
	})
	return file_proto_sandbox_controlv1_internal_proto_rawDescData
}

var file_proto_sandbox_controlv1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_sandbox_controlv1_internal_proto_goTypes = []any{
	(*StartWorkloadRequest)(nil),  // 0: sandbox.internal.v1.StartWorkloadRequest
	(*HttpReady)(nil),             // 1: sandbox.internal.v1.HttpReady
	(*StartWorkloadResponse)(nil), // 2: sandbox.internal.v1.StartWorkloadResponse
	(*NotifyForkedRequest)(nil),   // 3: sandbox.internal.v1.NotifyForkedRequest
	(*NotifyForkedNetwork)(nil),   // 4: sandbox.internal.v1.NotifyForkedNetwork
	(*VolumeMountEntry)(nil),      // 5: sandbox.internal.v1.VolumeMountEntry
	(*NotifyForkedResponse)(nil),  // 6: sandbox.internal.v1.NotifyForkedResponse
	(*ConfigureRequest)(nil),      // 7: sandbox.internal.v1.ConfigureRequest
	(*ConfigureResponse)(nil),     // 8: sandbox.internal.v1.ConfigureResponse
	(*PingRequest)(nil),           // 9: sandbox.internal.v1.PingRequest
	(*PingResponse)(nil),          // 10: sandbox.internal.v1.PingResponse
	nil,                           // 11: sandbox.internal.v1.StartWorkloadRequest.EnvEntry
	nil,                           // 12: sandbox.internal.v1.ConfigureRequest.EnvEntry
	nil,                           // 13: sandbox.internal.v1.ConfigureRequest.SecretsEntry
}
var file_proto_sandbox_controlv1_internal_proto_depIdxs = []int32{
	11, // 0: sandbox.internal.v1.StartWorkloadRequest.env:type_name -> sandbox.internal.v1.StartWorkloadRequest.EnvEntry
	1,  // 1: sandbox.internal.v1.StartWorkloadRequest.ready:type_name -> sandbox.internal.v1.HttpReady
	4,  // 2: sandbox.internal.v1.NotifyForkedRequest.network:type_name -> sandbox.internal.v1.NotifyForkedNetwork
	5,  // 3: sandbox.internal.v1.NotifyForkedRequest.volumes:type_name -> sandbox.internal.v1.VolumeMountEntry
	12, // 4: sandbox.internal.v1.ConfigureRequest.env:type_name -> sandbox.internal.v1.ConfigureRequest.EnvEntry
	13, // 5: sandbox.internal.v1.ConfigureRequest.secrets:type_name -> sandbox.internal.v1.ConfigureRequest.SecretsEntry
	3,  // 6: sandbox.internal.v1.Control.NotifyForked:input_type -> sandbox.internal.v1.NotifyForkedRequest
	7,  // 7: sandbox.internal.v1.Control.Configure:input_type -> sandbox.internal.v1.ConfigureRequest
	9,  // 8: sandbox.internal.v1.Control.Ping:input_type -> sandbox.internal.v1.PingRequest
	0,  // 9: sandbox.internal.v1.Control.StartWorkload:input_type -> sandbox.internal.v1.StartWorkloadRequest
	6,  // 10: sandbox.internal.v1.Control.NotifyForked:output_type -> sandbox.internal.v1.NotifyForkedResponse
	8,  // 11: sandbox.internal.v1.Control.Configure:output_type -> sandbox.internal.v1.ConfigureResponse
	10, // 12: sandbox.internal.v1.Control.Ping:output_type -> sandbox.internal.v1.PingResponse
	2,  // 13: sandbox.internal.v1.Control.StartWorkload:output_type -> sandbox.internal.v1.StartWorkloadResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_sandbox_controlv1_internal_proto_init() }
func file_proto_sandbox_controlv1_internal_proto_init() {
	if File_proto_sandbox_controlv1_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sandbox_controlv1_internal_proto_rawDesc), len(file_proto_sandbox_controlv1_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sandbox_controlv1_internal_proto_goTypes,
		DependencyIndexes: file_proto_sandbox_controlv1_internal_proto_depIdxs,
		MessageInfos:      file_proto_sandbox_controlv1_internal_proto_msgTypes,
	}.Build()
	File_proto_sandbox_controlv1_internal_proto = out.File
	file_proto_sandbox_controlv1_internal_proto_goTypes = nil
	file_proto_sandbox_controlv1_internal_proto_depIdxs = nil
}
