// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/sandbox/controlv1/internal.proto

// Internal host-to-guest control service (sandbox.internal.v1).
//
// This service carries secrets and the fork-correctness handshake. It is served
// by the guest agent on a DISTINCT vsock service port from the public Sandbox
// service. It is NEVER part of sandbox.v1.Sandbox, NEVER exposed on forkd :9091,
// and NEVER reachable from tenant code. The host (forkd) is the only caller.
//
// All three RPCs may carry sensitive material:
//   - NotifyForked: Entropy is raw CRNG seed material; HostWallClockNanos can
//     leak host timing. Neither is ever logged by host or guest.
//   - Configure: Env and Secrets are claim-time secret values injected into the
//     guest process environment. Values are NEVER logged or echoed by either side.
//   - Ping: carries no secrets; used for health checks.
//
// Package is versioned independently of sandbox.v1 with a one-major-version
// compatibility window (docs/api/runtime-protocol.md). The service name
// "sandbox.internal.v1.Control" is the vsock service discriminator used by the
// guest to accept connections on its dedicated control port.

package sandboxinternalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Control_NotifyForked_FullMethodName  = "/sandbox.internal.v1.Control/NotifyForked"
	Control_Configure_FullMethodName     = "/sandbox.internal.v1.Control/Configure"
	Control_Ping_FullMethodName          = "/sandbox.internal.v1.Control/Ping"
	Control_StartWorkload_FullMethodName = "/sandbox.internal.v1.Control/StartWorkload"
)

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Control is served by the guest agent on the dedicated internal vsock control
// port. Only the host (forkd) connects; no tenant or public surface exposes it.
// This service is INTENTIONALLY ABSENT from sandbox.v1.Sandbox; a test asserts
// the public service carries none of these methods.
type ControlClient interface {
	// NotifyForked tells the guest that a snapshot restore just occurred. The
	// guest must: (1) reseed the kernel CRNG with Entropy, (2) step CLOCK_REALTIME
	// to HostWallClockNanos, (3) reconfigure eth0 when Network is present, and
	// (4) mount per-fork volumes when Volumes is non-empty. The response reports
	// what the guest actually applied so the host can record fork-correctness
	// observability without logging the raw sensitive fields.
	NotifyForked(ctx context.Context, in *NotifyForkedRequest, opts ...grpc.CallOption) (*NotifyForkedResponse, error)
	// Configure delivers claim-time environment variables and secrets to the guest
	// after restore. THIS RPC CARRIES SECRET VALUES. Neither side ever logs Env or
	// Secrets values; only key names and counts are safe to log. This RPC is
	// host-trusted and must never be exposed on any public surface.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Ping checks that the guest agent is alive and returns its uptime. Carries no
	// secrets; safe to log.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// StartWorkload starts a declared serving workload during the template build
	// and keeps it running for the snapshot, so a fork wakes with the app already
	// listening (issue #460). The guest spawns the command in its OWN session so it
	// survives the build's exec process-group kill and the fork SIGUSR2 reset, and
	// when Ready is set blocks until the workload answers its port. Host-trusted
	// (build time only); INTENTIONALLY ABSENT from the public Sandbox surface, so a
	// tenant cannot start arbitrary detached processes outside its exec budget.
	StartWorkload(ctx context.Context, in *StartWorkloadRequest, opts ...grpc.CallOption) (*StartWorkloadResponse, error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) NotifyForked(ctx context.Context, in *NotifyForkedRequest, opts ...grpc.CallOption) (*NotifyForkedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyForkedResponse)
	err := c.cc.Invoke(ctx, Control_NotifyForked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, Control_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Control_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) StartWorkload(ctx context.Context, in *StartWorkloadRequest, opts ...grpc.CallOption) (*StartWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkloadResponse)
	err := c.cc.Invoke(ctx, Control_StartWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility.
//
// Control is served by the guest agent on the dedicated internal vsock control
// port. Only the host (forkd) connects; no tenant or public surface exposes it.
// This service is INTENTIONALLY ABSENT from sandbox.v1.Sandbox; a test asserts
// the public service carries none of these methods.
type ControlServer interface {
	// NotifyForked tells the guest that a snapshot restore just occurred. The
	// guest must: (1) reseed the kernel CRNG with Entropy, (2) step CLOCK_REALTIME
	// to HostWallClockNanos, (3) reconfigure eth0 when Network is present, and
	// (4) mount per-fork volumes when Volumes is non-empty. The response reports
	// what the guest actually applied so the host can record fork-correctness
	// observability without logging the raw sensitive fields.
	NotifyForked(context.Context, *NotifyForkedRequest) (*NotifyForkedResponse, error)
	// Configure delivers claim-time environment variables and secrets to the guest
	// after restore. THIS RPC CARRIES SECRET VALUES. Neither side ever logs Env or
	// Secrets values; only key names and counts are safe to log. This RPC is
	// host-trusted and must never be exposed on any public surface.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Ping checks that the guest agent is alive and returns its uptime. Carries no
	// secrets; safe to log.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// StartWorkload starts a declared serving workload during the template build
	// and keeps it running for the snapshot, so a fork wakes with the app already
	// listening (issue #460). The guest spawns the command in its OWN session so it
	// survives the build's exec process-group kill and the fork SIGUSR2 reset, and
	// when Ready is set blocks until the workload answers its port. Host-trusted
	// (build time only); INTENTIONALLY ABSENT from the public Sandbox surface, so a
	// tenant cannot start arbitrary detached processes outside its exec budget.
	StartWorkload(context.Context, *StartWorkloadRequest) (*StartWorkloadResponse, error)
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServer struct{}

func (UnimplementedControlServer) NotifyForked(context.Context, *NotifyForkedRequest) (*NotifyForkedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyForked not implemented")
}
func (UnimplementedControlServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedControlServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedControlServer) StartWorkload(context.Context, *StartWorkloadRequest) (*StartWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkload not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}
func (UnimplementedControlServer) testEmbeddedByValue()                 {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	// If the following call panics, it indicates UnimplementedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_NotifyForked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyForkedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).NotifyForked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_NotifyForked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).NotifyForked(ctx, req.(*NotifyForkedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_StartWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).StartWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_StartWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).StartWorkload(ctx, req.(*StartWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.internal.v1.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyForked",
			Handler:    _Control_NotifyForked_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Control_Configure_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Control_Ping_Handler,
		},
		{
			MethodName: "StartWorkload",
			Handler:    _Control_StartWorkload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sandbox/controlv1/internal.proto",
}
