// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/sandbox/controlv1/internal.proto

// Internal host-to-guest control service (sandbox.internal.v1).
//
// This service carries secrets and the fork-correctness handshake. It is served
// by the guest agent on a DISTINCT vsock service port from the public Sandbox
// service. It is NEVER part of sandbox.v1.Sandbox, NEVER exposed on forkd :9091,
// and NEVER reachable from tenant code. The host (forkd) is the only caller.
//
// All three RPCs may carry sensitive material:
//   - NotifyForked: Entropy is raw CRNG seed material; HostWallClockNanos can
//     leak host timing. Neither is ever logged by host or guest.
//   - Configure: Env and Secrets are claim-time secret values injected into the
//     guest process environment. Values are NEVER logged or echoed by either side.
//   - Ping: carries no secrets; used for health checks.
//
// Package is versioned independently of sandbox.v1 with a one-major-version
// compatibility window (docs/api/runtime-protocol.md). The service name
// "sandbox.internal.v1.Control" is the vsock service discriminator used by the
// guest to accept connections on its dedicated control port.

package sandboxinternalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotifyForkedRequest mirrors internal/vsock.NotifyForkedRequest field-for-field.
//
// Entropy and host_wall_clock_nanos are SENSITIVE: Entropy is raw CRNG seed
// material and the clock can leak host timing. Neither field is ever logged by
// host or guest; only applied-step magnitudes and reseed success are logged.
type NotifyForkedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// generation is the fork sequence number; the guest uses it to detect
	// replayed or out-of-order notifications.
	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// host_wall_clock_nanos is the host wall time at fork time, in nanoseconds
	// since the Unix epoch. The guest steps CLOCK_REALTIME to this value to
	// correct the clock drift introduced by snapshot/restore.
	// SENSITIVE: do not log.
	HostWallClockNanos int64 `protobuf:"varint,2,opt,name=host_wall_clock_nanos,json=hostWallClockNanos,proto3" json:"host_wall_clock_nanos,omitempty"`
	// entropy is fresh host CRNG output delivered to the guest so it can reseed
	// its kernel entropy pool after restore. Forks share the snapshot's entropy
	// state; without this injection every fork starts from the same seed.
	// SENSITIVE: do not log.
	Entropy []byte `protobuf:"bytes,3,opt,name=entropy,proto3" json:"entropy,omitempty"`
	// network, when set, carries this fork's per-fork network identity (distinct
	// guest IP, gateway, prefix, and optional MAC). The guest reconfigures eth0
	// on receipt. Fields are plain addresses and safe to log.
	Network *NotifyForkedNetwork `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	// volumes is the per-fork volume mount table. The host rebinds each backing
	// drive before sending this notification; the guest mounts each entry at its
	// designated path. Empty means no volumes. Device nodes and paths are safe
	// to log.
	Volumes       []*VolumeMountEntry `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyForkedRequest) Reset() {
	*x = NotifyForkedRequest{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyForkedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyForkedRequest) ProtoMessage() {}

func (x *NotifyForkedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyForkedRequest.ProtoReflect.Descriptor instead.
func (*NotifyForkedRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyForkedRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *NotifyForkedRequest) GetHostWallClockNanos() int64 {
	if x != nil {
		return x.HostWallClockNanos
	}
	return 0
}

func (x *NotifyForkedRequest) GetEntropy() []byte {
	if x != nil {
		return x.Entropy
	}
	return nil
}

func (x *NotifyForkedRequest) GetNetwork() *NotifyForkedNetwork {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *NotifyForkedRequest) GetVolumes() []*VolumeMountEntry {
	if x != nil {
		return x.Volumes
	}
	return nil
}

// NotifyForkedNetwork mirrors internal/vsock.NotifyForkedNetwork field-for-field.
// All fields are plain network addresses and safe to log.
type NotifyForkedNetwork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// guest_ip is the IPv4 address assigned to eth0 in the guest (e.g.
	// "10.0.1.2").
	GuestIp string `protobuf:"bytes,1,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	// gateway_ip is the default route target, the host side of the per-fork /30
	// (e.g. "10.0.1.1").
	GatewayIp string `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	// prefix_len is the network prefix length (e.g. 30 for a /30).
	PrefixLen int32 `protobuf:"varint,3,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	// guest_mac, when non-empty, is this fork's distinct eth0 hardware address
	// (e.g. "02:ab:cd:ef:01:02"). The guest sets it before bringing the link up
	// so each fork has a distinct MAC. Empty leaves the snapshot-baked MAC in
	// place.
	GuestMac string `protobuf:"bytes,4,opt,name=guest_mac,json=guestMac,proto3" json:"guest_mac,omitempty"`
	// resolver_ip, when non-empty, is the DNS resolver the guest must use. The
	// guest writes it as the sole nameserver in /etc/resolv.conf. Empty leaves
	// resolv.conf untouched.
	ResolverIp    string `protobuf:"bytes,5,opt,name=resolver_ip,json=resolverIp,proto3" json:"resolver_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyForkedNetwork) Reset() {
	*x = NotifyForkedNetwork{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyForkedNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyForkedNetwork) ProtoMessage() {}

func (x *NotifyForkedNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyForkedNetwork.ProtoReflect.Descriptor instead.
func (*NotifyForkedNetwork) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyForkedNetwork) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *NotifyForkedNetwork) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *NotifyForkedNetwork) GetPrefixLen() int32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *NotifyForkedNetwork) GetGuestMac() string {
	if x != nil {
		return x.GuestMac
	}
	return ""
}

func (x *NotifyForkedNetwork) GetResolverIp() string {
	if x != nil {
		return x.ResolverIp
	}
	return ""
}

// VolumeMountEntry mirrors internal/vsock.VolumeMountEntry field-for-field.
// All fields are config values, not secrets, and safe to log.
type VolumeMountEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device is the guest block device node (e.g. "/dev/vdb") assigned by the
	// drive attach order (rootfs is /dev/vda; the i-th volume is /dev/vd{b+i}).
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// mount_path is where the guest mounts the device.
	MountPath string `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	// read_only attaches the device MS_RDONLY so a shared or read-only volume
	// cannot be modified by the guest.
	ReadOnly      bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMountEntry) Reset() {
	*x = VolumeMountEntry{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMountEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMountEntry) ProtoMessage() {}

func (x *VolumeMountEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMountEntry.ProtoReflect.Descriptor instead.
func (*VolumeMountEntry) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeMountEntry) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *VolumeMountEntry) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *VolumeMountEntry) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// NotifyForkedResponse mirrors internal/vsock.NotifyForkedResponse field-for-field.
// All fields are observability counters and magnitudes, never raw secret values.
type NotifyForkedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// applied_clock_step_nanos is the signed adjustment applied to CLOCK_REALTIME
	// in nanoseconds (0 when drift was within the guest's tolerance threshold).
	AppliedClockStepNanos int64 `protobuf:"varint,1,opt,name=applied_clock_step_nanos,json=appliedClockStepNanos,proto3" json:"applied_clock_step_nanos,omitempty"`
	// reseeded_rng is true when at least one entropy-injection path into the
	// kernel pool succeeded.
	ReseededRng bool `protobuf:"varint,2,opt,name=reseeded_rng,json=reseededRng,proto3" json:"reseeded_rng,omitempty"`
	// signaled_processes is the count of userspace processes that received the
	// CRNG-reseed signal so they can reinitialize their own PRNGs.
	SignaledProcesses int32 `protobuf:"varint,3,opt,name=signaled_processes,json=signaledProcesses,proto3" json:"signaled_processes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotifyForkedResponse) Reset() {
	*x = NotifyForkedResponse{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyForkedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyForkedResponse) ProtoMessage() {}

func (x *NotifyForkedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyForkedResponse.ProtoReflect.Descriptor instead.
func (*NotifyForkedResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyForkedResponse) GetAppliedClockStepNanos() int64 {
	if x != nil {
		return x.AppliedClockStepNanos
	}
	return 0
}

func (x *NotifyForkedResponse) GetReseededRng() bool {
	if x != nil {
		return x.ReseededRng
	}
	return false
}

func (x *NotifyForkedResponse) GetSignaledProcesses() int32 {
	if x != nil {
		return x.SignaledProcesses
	}
	return 0
}

// ConfigureRequest mirrors internal/vsock.ConfigureRequest field-for-field.
//
// THIS MESSAGE CARRIES SECRET VALUES. env and secrets values are claim-time
// credentials injected into the guest process environment. Neither side ever
// logs values; only key names and entry counts are safe to log. This message
// must never appear on any public service or surface.
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// env is the set of environment variables to merge into the guest environment.
	// Values may be secret; log only keys and the entry count.
	Env map[string]string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// secrets is the set of secret values (e.g. API tokens, credentials) to
	// inject. Values are NEVER logged or echoed by either side.
	Secrets       map[string]string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ConfigureRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// ConfigureResponse acknowledges successful delivery of Configure. It carries
// no payload; success is indicated by the absence of an RPC error.
type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{5}
}

// PingRequest carries no fields; it is a struct so future knobs can be added
// without changing the wire tag.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{6}
}

// PingResponse mirrors internal/vsock.PingResponse field-for-field.
// Carries no secrets; safe to log.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uptime_seconds is the guest agent process uptime in fractional seconds,
	// matching the vsock protocol's float64 "uptime_seconds" JSON field.
	UptimeSeconds float64 `protobuf:"fixed64,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sandbox_controlv1_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_sandbox_controlv1_internal_proto_rawDescGZIP(), []int{7}
}

func (x *PingResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_sandbox_controlv1_internal_proto protoreflect.FileDescriptor

const file_proto_sandbox_controlv1_internal_proto_rawDesc = "" +
	"\n" +
	"&proto/sandbox/controlv1/internal.proto\x12\x13sandbox.internal.v1\"\x87\x02\n" +
	"\x13NotifyForkedRequest\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x121\n" +
	"\x15host_wall_clock_nanos\x18\x02 \x01(\x03R\x12hostWallClockNanos\x12\x18\n" +
	"\aentropy\x18\x03 \x01(\fR\aentropy\x12B\n" +
	"\anetwork\x18\x04 \x01(\v2(.sandbox.internal.v1.NotifyForkedNetworkR\anetwork\x12?\n" +
	"\avolumes\x18\x05 \x03(\v2%.sandbox.internal.v1.VolumeMountEntryR\avolumes\"\xac\x01\n" +
	"\x13NotifyForkedNetwork\x12\x19\n" +
	"\bguest_ip\x18\x01 \x01(\tR\aguestIp\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x02 \x01(\tR\tgatewayIp\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x03 \x01(\x05R\tprefixLen\x12\x1b\n" +
	"\tguest_mac\x18\x04 \x01(\tR\bguestMac\x12\x1f\n" +
	"\vresolver_ip\x18\x05 \x01(\tR\n" +
	"resolverIp\"f\n" +
	"\x10VolumeMountEntry\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xa1\x01\n" +
	"\x14NotifyForkedResponse\x127\n" +
	"\x18applied_clock_step_nanos\x18\x01 \x01(\x03R\x15appliedClockStepNanos\x12!\n" +
	"\freseeded_rng\x18\x02 \x01(\bR\vreseededRng\x12-\n" +
	"\x12signaled_processes\x18\x03 \x01(\x05R\x11signaledProcesses\"\x96\x02\n" +
	"\x10ConfigureRequest\x12@\n" +
	"\x03env\x18\x01 \x03(\v2..sandbox.internal.v1.ConfigureRequest.EnvEntryR\x03env\x12L\n" +
	"\asecrets\x18\x02 \x03(\v22.sandbox.internal.v1.ConfigureRequest.SecretsEntryR\asecrets\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ConfigureResponse\"\r\n" +
	"\vPingRequest\"5\n" +
	"\fPingResponse\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x01R\ruptimeSeconds2\x97\x02\n" +
	"\aControl\x12c\n" +
	"\fNotifyForked\x12(.sandbox.internal.v1.NotifyForkedRequest\x1a).sandbox.internal.v1.NotifyForkedResponse\x12Z\n" +
	"\tConfigure\x12%.sandbox.internal.v1.ConfigureRequest\x1a&.sandbox.internal.v1.ConfigureResponse\x12K\n" +
	"\x04Ping\x12 .sandbox.internal.v1.PingRequest\x1a!.sandbox.internal.v1.PingResponseB;Z9mitos.run/mitos/proto/sandbox/controlv1;sandboxinternalv1b\x06proto3"

var (
	file_proto_sandbox_controlv1_internal_proto_rawDescOnce sync.Once
	file_proto_sandbox_controlv1_internal_proto_rawDescData []byte
)

func file_proto_sandbox_controlv1_internal_proto_rawDescGZIP() []byte {
	file_proto_sandbox_controlv1_internal_proto_rawDescOnce.Do(func() {
		file_proto_sandbox_controlv1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sandbox_controlv1_internal_proto_rawDesc), len(file_proto_sandbox_controlv1_internal_proto_rawDesc)))
	})
	return file_proto_sandbox_controlv1_internal_proto_rawDescData
}

var file_proto_sandbox_controlv1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_sandbox_controlv1_internal_proto_goTypes = []any{
	(*NotifyForkedRequest)(nil),  // 0: sandbox.internal.v1.NotifyForkedRequest
	(*NotifyForkedNetwork)(nil),  // 1: sandbox.internal.v1.NotifyForkedNetwork
	(*VolumeMountEntry)(nil),     // 2: sandbox.internal.v1.VolumeMountEntry
	(*NotifyForkedResponse)(nil), // 3: sandbox.internal.v1.NotifyForkedResponse
	(*ConfigureRequest)(nil),     // 4: sandbox.internal.v1.ConfigureRequest
	(*ConfigureResponse)(nil),    // 5: sandbox.internal.v1.ConfigureResponse
	(*PingRequest)(nil),          // 6: sandbox.internal.v1.PingRequest
	(*PingResponse)(nil),         // 7: sandbox.internal.v1.PingResponse
	nil,                          // 8: sandbox.internal.v1.ConfigureRequest.EnvEntry
	nil,                          // 9: sandbox.internal.v1.ConfigureRequest.SecretsEntry
}
var file_proto_sandbox_controlv1_internal_proto_depIdxs = []int32{
	1, // 0: sandbox.internal.v1.NotifyForkedRequest.network:type_name -> sandbox.internal.v1.NotifyForkedNetwork
	2, // 1: sandbox.internal.v1.NotifyForkedRequest.volumes:type_name -> sandbox.internal.v1.VolumeMountEntry
	8, // 2: sandbox.internal.v1.ConfigureRequest.env:type_name -> sandbox.internal.v1.ConfigureRequest.EnvEntry
	9, // 3: sandbox.internal.v1.ConfigureRequest.secrets:type_name -> sandbox.internal.v1.ConfigureRequest.SecretsEntry
	0, // 4: sandbox.internal.v1.Control.NotifyForked:input_type -> sandbox.internal.v1.NotifyForkedRequest
	4, // 5: sandbox.internal.v1.Control.Configure:input_type -> sandbox.internal.v1.ConfigureRequest
	6, // 6: sandbox.internal.v1.Control.Ping:input_type -> sandbox.internal.v1.PingRequest
	3, // 7: sandbox.internal.v1.Control.NotifyForked:output_type -> sandbox.internal.v1.NotifyForkedResponse
	5, // 8: sandbox.internal.v1.Control.Configure:output_type -> sandbox.internal.v1.ConfigureResponse
	7, // 9: sandbox.internal.v1.Control.Ping:output_type -> sandbox.internal.v1.PingResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sandbox_controlv1_internal_proto_init() }
func file_proto_sandbox_controlv1_internal_proto_init() {
	if File_proto_sandbox_controlv1_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sandbox_controlv1_internal_proto_rawDesc), len(file_proto_sandbox_controlv1_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sandbox_controlv1_internal_proto_goTypes,
		DependencyIndexes: file_proto_sandbox_controlv1_internal_proto_depIdxs,
		MessageInfos:      file_proto_sandbox_controlv1_internal_proto_msgTypes,
	}.Build()
	File_proto_sandbox_controlv1_internal_proto = out.File
	file_proto_sandbox_controlv1_internal_proto_goTypes = nil
	file_proto_sandbox_controlv1_internal_proto_depIdxs = nil
}
