// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/sandbox/v1/sandbox.proto

// The Sandbox runtime protocol (API v2, docs/api/v2-spec.md section 4).
//
// This is the NORMATIVE CONTRACT for the in-sandbox runtime surface: streaming
// exec/PTY, file IO, directory listing, filesystem watch, archive transfer,
// process inspection, signals, port-forward, and guest vitals; plus the
// budget-gated self-service RPCs (Fork, Checkpoint, ExtendLifetime, Budget)
// that the controller materializes declaratively (issue #25 capability budgets).
//
// One protocol is intended to ride three transports (vsock in-guest,
// cluster-internal, browser). Today the runtime surface is served by the ad-hoc
// JSON-over-HTTP sandbox API on forkd :9091 and the JSON-lines vsock protocol to
// the guest agent (internal/vsock, guest/agent). Those WORK and remain in force.
// This proto fixes the target contract so the wire migration (guest agent ->
// this service, forkd bridge, three transports, KVM e2e) is a well-scoped set of
// follow-up slices. See docs/api/runtime-protocol.md and ADR 0007.
//
// The package is versioned (sandbox.v1) so the runtime protocol can version
// independently of the forkd control-plane proto, with a one-major-version
// compatibility window (docs/api/runtime-protocol.md).

package sandboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sandbox_Exec_FullMethodName           = "/sandbox.v1.Sandbox/Exec"
	Sandbox_ReadFile_FullMethodName       = "/sandbox.v1.Sandbox/ReadFile"
	Sandbox_WriteFile_FullMethodName      = "/sandbox.v1.Sandbox/WriteFile"
	Sandbox_List_FullMethodName           = "/sandbox.v1.Sandbox/List"
	Sandbox_Stat_FullMethodName           = "/sandbox.v1.Sandbox/Stat"
	Sandbox_Archive_FullMethodName        = "/sandbox.v1.Sandbox/Archive"
	Sandbox_Watch_FullMethodName          = "/sandbox.v1.Sandbox/Watch"
	Sandbox_Processes_FullMethodName      = "/sandbox.v1.Sandbox/Processes"
	Sandbox_Signal_FullMethodName         = "/sandbox.v1.Sandbox/Signal"
	Sandbox_PortForward_FullMethodName    = "/sandbox.v1.Sandbox/PortForward"
	Sandbox_Fork_FullMethodName           = "/sandbox.v1.Sandbox/Fork"
	Sandbox_Checkpoint_FullMethodName     = "/sandbox.v1.Sandbox/Checkpoint"
	Sandbox_ExtendLifetime_FullMethodName = "/sandbox.v1.Sandbox/ExtendLifetime"
	Sandbox_Budget_FullMethodName         = "/sandbox.v1.Sandbox/Budget"
	Sandbox_Vitals_FullMethodName         = "/sandbox.v1.Sandbox/Vitals"
)

// SandboxClient is the client API for Sandbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sandbox is the runtime surface a caller has against ONE sandbox: its own
// sandbox. Every RPC is implicitly scoped to the caller's sandbox by the
// transport credential (the per-sandbox bearer token at the forkd edge today,
// an attenuated capability token under issue #25). Deliberately ABSENT, by
// design, are Delete of OTHER sandboxes, pool mutation, and workspace
// administration: those are creator-scope, declarative-only operations that the
// controller owns. me.exit() terminates only the caller and is modeled as a
// Signal to the caller's own init, not a cross-sandbox Delete.
type SandboxClient interface {
	// Exec runs a command and streams its IO. The client sends one ExecRequest
	// with the open oneof (cmd, env, cwd, pty), then zero or more ExecRequest with
	// the stdin oneof to feed stdin and resize oneof to resize a PTY. The server
	// streams stdout/stderr chunks and a terminal exit. This replaces both the
	// one-shot POST /v1/exec and the streaming POST /v1/exec/stream and the PTY
	// WebSocket GET /v1/pty: a non-PTY Exec is a streaming exec, a PTY Exec
	// (open.pty set) is the interactive terminal, both over the one bidi stream.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error)
	// ReadFile streams the bytes of one file. Replaces POST /v1/files/read.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	// WriteFile streams bytes into one file. The first WriteFileRequest carries
	// the path and mode; subsequent messages carry content chunks. Replaces
	// POST /v1/files/write.
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResult], error)
	// List enumerates a directory with AIP-158 pagination and filtering. Replaces
	// POST /v1/files/list.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Stat returns metadata for one path without reading its contents.
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*FileInfo, error)
	// Archive tars a subtree and streams the tar bytes (download), or, when
	// direction is UNTAR, accepts a tar to extract. Replaces the vsock tar_dir /
	// untar_dir workspace-transfer path. For UNTAR the client uses the streaming
	// WriteFile-style upload via ArchiveUploadRequest (see PortForward note: this
	// download-only RPC keeps the common path simple; the symmetric upload is a
	// follow-up streaming RPC, see docs/api/runtime-protocol.md).
	Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	// Watch streams filesystem change events for a subtree until the client
	// cancels. New surface in v2 (no current HTTP/vsock equivalent).
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FsEvent], error)
	// Processes lists the guest process table. New surface in v2.
	Processes(ctx context.Context, in *ProcessesRequest, opts ...grpc.CallOption) (*ProcessList, error)
	// Signal delivers a POSIX signal to a process in the guest. me.exit() is a
	// SIGTERM to the caller's own init (pid 1) and is the ONLY way a sandbox ends
	// itself. New surface in v2.
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	// PortForward proxies a guest TCP port over a bidirectional byte stream. Each
	// Frame carries a slice of one direction's bytes. New surface in v2.
	PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
	// Fork forks N sibling sandboxes from this live sandbox. Returns a
	// long-running Operation handle the caller polls; the controller materializes
	// the N siblings declaratively. Budget-gated by the fork allowance.
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*Operation, error)
	// Checkpoint captures this sandbox's live state as a workspace Revision.
	// Returns the Revision handle. Budget-gated by the checkpoint allowance.
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*Revision, error)
	// ExtendLifetime extends this sandbox's lease. Returns the new Lease.
	// Budget-gated by the lifetime allowance.
	ExtendLifetime(ctx context.Context, in *ExtendRequest, opts ...grpc.CallOption) (*Lease, error)
	// Budget reports the caller's remaining self-service allowances.
	Budget(ctx context.Context, in *BudgetRequest, opts ...grpc.CallOption) (*BudgetStatus, error)
	// Vitals streams guest health samples (cpu steal, memory vs balloon, process
	// count) until the client cancels. New surface in v2.
	Vitals(ctx context.Context, in *VitalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GuestVitals], error)
}

type sandboxClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxClient(cc grpc.ClientConnInterface) SandboxClient {
	return &sandboxClient{cc}
}

func (c *sandboxClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[0], Sandbox_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ExecClient = grpc.BidiStreamingClient[ExecRequest, ExecResponse]

func (c *sandboxClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[1], Sandbox_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ReadFileClient = grpc.ServerStreamingClient[Chunk]

func (c *sandboxClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[2], Sandbox_WriteFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileRequest, WriteFileResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_WriteFileClient = grpc.ClientStreamingClient[WriteFileRequest, WriteFileResult]

func (c *sandboxClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, Sandbox_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*FileInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileInfo)
	err := c.cc.Invoke(ctx, Sandbox_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[3], Sandbox_Archive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArchiveRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ArchiveClient = grpc.ServerStreamingClient[Chunk]

func (c *sandboxClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[4], Sandbox_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, FsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_WatchClient = grpc.ServerStreamingClient[FsEvent]

func (c *sandboxClient) Processes(ctx context.Context, in *ProcessesRequest, opts ...grpc.CallOption) (*ProcessList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, Sandbox_Processes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, Sandbox_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[5], Sandbox_PortForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_PortForwardClient = grpc.BidiStreamingClient[Frame, Frame]

func (c *sandboxClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, Sandbox_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*Revision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Revision)
	err := c.cc.Invoke(ctx, Sandbox_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) ExtendLifetime(ctx context.Context, in *ExtendRequest, opts ...grpc.CallOption) (*Lease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lease)
	err := c.cc.Invoke(ctx, Sandbox_ExtendLifetime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) Budget(ctx context.Context, in *BudgetRequest, opts ...grpc.CallOption) (*BudgetStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetStatus)
	err := c.cc.Invoke(ctx, Sandbox_Budget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxClient) Vitals(ctx context.Context, in *VitalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GuestVitals], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandbox_ServiceDesc.Streams[6], Sandbox_Vitals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VitalsRequest, GuestVitals]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_VitalsClient = grpc.ServerStreamingClient[GuestVitals]

// SandboxServer is the server API for Sandbox service.
// All implementations must embed UnimplementedSandboxServer
// for forward compatibility.
//
// Sandbox is the runtime surface a caller has against ONE sandbox: its own
// sandbox. Every RPC is implicitly scoped to the caller's sandbox by the
// transport credential (the per-sandbox bearer token at the forkd edge today,
// an attenuated capability token under issue #25). Deliberately ABSENT, by
// design, are Delete of OTHER sandboxes, pool mutation, and workspace
// administration: those are creator-scope, declarative-only operations that the
// controller owns. me.exit() terminates only the caller and is modeled as a
// Signal to the caller's own init, not a cross-sandbox Delete.
type SandboxServer interface {
	// Exec runs a command and streams its IO. The client sends one ExecRequest
	// with the open oneof (cmd, env, cwd, pty), then zero or more ExecRequest with
	// the stdin oneof to feed stdin and resize oneof to resize a PTY. The server
	// streams stdout/stderr chunks and a terminal exit. This replaces both the
	// one-shot POST /v1/exec and the streaming POST /v1/exec/stream and the PTY
	// WebSocket GET /v1/pty: a non-PTY Exec is a streaming exec, a PTY Exec
	// (open.pty set) is the interactive terminal, both over the one bidi stream.
	Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error
	// ReadFile streams the bytes of one file. Replaces POST /v1/files/read.
	ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[Chunk]) error
	// WriteFile streams bytes into one file. The first WriteFileRequest carries
	// the path and mode; subsequent messages carry content chunks. Replaces
	// POST /v1/files/write.
	WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResult]) error
	// List enumerates a directory with AIP-158 pagination and filtering. Replaces
	// POST /v1/files/list.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Stat returns metadata for one path without reading its contents.
	Stat(context.Context, *StatRequest) (*FileInfo, error)
	// Archive tars a subtree and streams the tar bytes (download), or, when
	// direction is UNTAR, accepts a tar to extract. Replaces the vsock tar_dir /
	// untar_dir workspace-transfer path. For UNTAR the client uses the streaming
	// WriteFile-style upload via ArchiveUploadRequest (see PortForward note: this
	// download-only RPC keeps the common path simple; the symmetric upload is a
	// follow-up streaming RPC, see docs/api/runtime-protocol.md).
	Archive(*ArchiveRequest, grpc.ServerStreamingServer[Chunk]) error
	// Watch streams filesystem change events for a subtree until the client
	// cancels. New surface in v2 (no current HTTP/vsock equivalent).
	Watch(*WatchRequest, grpc.ServerStreamingServer[FsEvent]) error
	// Processes lists the guest process table. New surface in v2.
	Processes(context.Context, *ProcessesRequest) (*ProcessList, error)
	// Signal delivers a POSIX signal to a process in the guest. me.exit() is a
	// SIGTERM to the caller's own init (pid 1) and is the ONLY way a sandbox ends
	// itself. New surface in v2.
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	// PortForward proxies a guest TCP port over a bidirectional byte stream. Each
	// Frame carries a slice of one direction's bytes. New surface in v2.
	PortForward(grpc.BidiStreamingServer[Frame, Frame]) error
	// Fork forks N sibling sandboxes from this live sandbox. Returns a
	// long-running Operation handle the caller polls; the controller materializes
	// the N siblings declaratively. Budget-gated by the fork allowance.
	Fork(context.Context, *ForkRequest) (*Operation, error)
	// Checkpoint captures this sandbox's live state as a workspace Revision.
	// Returns the Revision handle. Budget-gated by the checkpoint allowance.
	Checkpoint(context.Context, *CheckpointRequest) (*Revision, error)
	// ExtendLifetime extends this sandbox's lease. Returns the new Lease.
	// Budget-gated by the lifetime allowance.
	ExtendLifetime(context.Context, *ExtendRequest) (*Lease, error)
	// Budget reports the caller's remaining self-service allowances.
	Budget(context.Context, *BudgetRequest) (*BudgetStatus, error)
	// Vitals streams guest health samples (cpu steal, memory vs balloon, process
	// count) until the client cancels. New surface in v2.
	Vitals(*VitalsRequest, grpc.ServerStreamingServer[GuestVitals]) error
	mustEmbedUnimplementedSandboxServer()
}

// UnimplementedSandboxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServer struct{}

func (UnimplementedSandboxServer) Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxServer) ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxServer) WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResult]) error {
	return status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSandboxServer) Stat(context.Context, *StatRequest) (*FileInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedSandboxServer) Archive(*ArchiveRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedSandboxServer) Watch(*WatchRequest, grpc.ServerStreamingServer[FsEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSandboxServer) Processes(context.Context, *ProcessesRequest) (*ProcessList, error) {
	return nil, status.Error(codes.Unimplemented, "method Processes not implemented")
}
func (UnimplementedSandboxServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSandboxServer) PortForward(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method PortForward not implemented")
}
func (UnimplementedSandboxServer) Fork(context.Context, *ForkRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedSandboxServer) Checkpoint(context.Context, *CheckpointRequest) (*Revision, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedSandboxServer) ExtendLifetime(context.Context, *ExtendRequest) (*Lease, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendLifetime not implemented")
}
func (UnimplementedSandboxServer) Budget(context.Context, *BudgetRequest) (*BudgetStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Budget not implemented")
}
func (UnimplementedSandboxServer) Vitals(*VitalsRequest, grpc.ServerStreamingServer[GuestVitals]) error {
	return status.Error(codes.Unimplemented, "method Vitals not implemented")
}
func (UnimplementedSandboxServer) mustEmbedUnimplementedSandboxServer() {}
func (UnimplementedSandboxServer) testEmbeddedByValue()                 {}

// UnsafeSandboxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServer will
// result in compilation errors.
type UnsafeSandboxServer interface {
	mustEmbedUnimplementedSandboxServer()
}

func RegisterSandboxServer(s grpc.ServiceRegistrar, srv SandboxServer) {
	// If the following call panics, it indicates UnimplementedSandboxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sandbox_ServiceDesc, srv)
}

func _Sandbox_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxServer).Exec(&grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ExecServer = grpc.BidiStreamingServer[ExecRequest, ExecResponse]

func _Sandbox_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServer).ReadFile(m, &grpc.GenericServerStream[ReadFileRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ReadFileServer = grpc.ServerStreamingServer[Chunk]

func _Sandbox_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxServer).WriteFile(&grpc.GenericServerStream[WriteFileRequest, WriteFileResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_WriteFileServer = grpc.ClientStreamingServer[WriteFileRequest, WriteFileResult]

func _Sandbox_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_Archive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ArchiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServer).Archive(m, &grpc.GenericServerStream[ArchiveRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_ArchiveServer = grpc.ServerStreamingServer[Chunk]

func _Sandbox_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServer).Watch(m, &grpc.GenericServerStream[WatchRequest, FsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_WatchServer = grpc.ServerStreamingServer[FsEvent]

func _Sandbox_Processes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Processes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Processes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Processes(ctx, req.(*ProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_PortForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxServer).PortForward(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_PortForwardServer = grpc.BidiStreamingServer[Frame, Frame]

func _Sandbox_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_ExtendLifetime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).ExtendLifetime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_ExtendLifetime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).ExtendLifetime(ctx, req.(*ExtendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_Budget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServer).Budget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandbox_Budget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServer).Budget(ctx, req.(*BudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandbox_Vitals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VitalsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxServer).Vitals(m, &grpc.GenericServerStream[VitalsRequest, GuestVitals]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandbox_VitalsServer = grpc.ServerStreamingServer[GuestVitals]

// Sandbox_ServiceDesc is the grpc.ServiceDesc for Sandbox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sandbox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.v1.Sandbox",
	HandlerType: (*SandboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Sandbox_List_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Sandbox_Stat_Handler,
		},
		{
			MethodName: "Processes",
			Handler:    _Sandbox_Processes_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _Sandbox_Signal_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _Sandbox_Fork_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Sandbox_Checkpoint_Handler,
		},
		{
			MethodName: "ExtendLifetime",
			Handler:    _Sandbox_ExtendLifetime_Handler,
		},
		{
			MethodName: "Budget",
			Handler:    _Sandbox_Budget_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _Sandbox_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadFile",
			Handler:       _Sandbox_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _Sandbox_WriteFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Archive",
			Handler:       _Sandbox_Archive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _Sandbox_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PortForward",
			Handler:       _Sandbox_PortForward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Vitals",
			Handler:       _Sandbox_Vitals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sandbox/v1/sandbox.proto",
}
