// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/sandbox/v1/sandbox.proto

// The Sandbox runtime protocol (API v2, docs/api/v2-spec.md section 4).
//
// This is the NORMATIVE CONTRACT for the in-sandbox runtime surface: streaming
// exec/PTY, file IO, directory listing, filesystem watch, archive transfer,
// process inspection, signals, port-forward, and guest vitals; plus the
// budget-gated self-service RPCs (Fork, Checkpoint, ExtendLifetime, Budget)
// that the controller materializes declaratively (issue #25 capability budgets).
//
// One protocol is intended to ride three transports (vsock in-guest,
// cluster-internal, browser). Today the runtime surface is served by the ad-hoc
// JSON-over-HTTP sandbox API on forkd :9091 and the JSON-lines vsock protocol to
// the guest agent (internal/vsock, guest/agent). Those WORK and remain in force.
// This proto fixes the target contract so the wire migration (guest agent ->
// this service, forkd bridge, three transports, KVM e2e) is a well-scoped set of
// follow-up slices. See docs/api/runtime-protocol.md and ADR 0007.
//
// The package is versioned (sandbox.v1) so the runtime protocol can version
// independently of the forkd control-plane proto, with a one-major-version
// compatibility window (docs/api/runtime-protocol.md).
package sandboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "mitos.run/mitos/proto/sandbox/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SandboxName is the fully-qualified name of the Sandbox service.
	SandboxName = "sandbox.v1.Sandbox"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SandboxExecProcedure is the fully-qualified name of the Sandbox's Exec RPC.
	SandboxExecProcedure = "/sandbox.v1.Sandbox/Exec"
	// SandboxExecStreamProcedure is the fully-qualified name of the Sandbox's ExecStream RPC.
	SandboxExecStreamProcedure = "/sandbox.v1.Sandbox/ExecStream"
	// SandboxReadFileProcedure is the fully-qualified name of the Sandbox's ReadFile RPC.
	SandboxReadFileProcedure = "/sandbox.v1.Sandbox/ReadFile"
	// SandboxWriteFileProcedure is the fully-qualified name of the Sandbox's WriteFile RPC.
	SandboxWriteFileProcedure = "/sandbox.v1.Sandbox/WriteFile"
	// SandboxListProcedure is the fully-qualified name of the Sandbox's List RPC.
	SandboxListProcedure = "/sandbox.v1.Sandbox/List"
	// SandboxStatProcedure is the fully-qualified name of the Sandbox's Stat RPC.
	SandboxStatProcedure = "/sandbox.v1.Sandbox/Stat"
	// SandboxArchiveProcedure is the fully-qualified name of the Sandbox's Archive RPC.
	SandboxArchiveProcedure = "/sandbox.v1.Sandbox/Archive"
	// SandboxWatchProcedure is the fully-qualified name of the Sandbox's Watch RPC.
	SandboxWatchProcedure = "/sandbox.v1.Sandbox/Watch"
	// SandboxProcessesProcedure is the fully-qualified name of the Sandbox's Processes RPC.
	SandboxProcessesProcedure = "/sandbox.v1.Sandbox/Processes"
	// SandboxSignalProcedure is the fully-qualified name of the Sandbox's Signal RPC.
	SandboxSignalProcedure = "/sandbox.v1.Sandbox/Signal"
	// SandboxPortForwardProcedure is the fully-qualified name of the Sandbox's PortForward RPC.
	SandboxPortForwardProcedure = "/sandbox.v1.Sandbox/PortForward"
	// SandboxForkProcedure is the fully-qualified name of the Sandbox's Fork RPC.
	SandboxForkProcedure = "/sandbox.v1.Sandbox/Fork"
	// SandboxCheckpointProcedure is the fully-qualified name of the Sandbox's Checkpoint RPC.
	SandboxCheckpointProcedure = "/sandbox.v1.Sandbox/Checkpoint"
	// SandboxExtendLifetimeProcedure is the fully-qualified name of the Sandbox's ExtendLifetime RPC.
	SandboxExtendLifetimeProcedure = "/sandbox.v1.Sandbox/ExtendLifetime"
	// SandboxBudgetProcedure is the fully-qualified name of the Sandbox's Budget RPC.
	SandboxBudgetProcedure = "/sandbox.v1.Sandbox/Budget"
	// SandboxVitalsProcedure is the fully-qualified name of the Sandbox's Vitals RPC.
	SandboxVitalsProcedure = "/sandbox.v1.Sandbox/Vitals"
	// SandboxRunCodeProcedure is the fully-qualified name of the Sandbox's RunCode RPC.
	SandboxRunCodeProcedure = "/sandbox.v1.Sandbox/RunCode"
	// SandboxRunCodeStreamProcedure is the fully-qualified name of the Sandbox's RunCodeStream RPC.
	SandboxRunCodeStreamProcedure = "/sandbox.v1.Sandbox/RunCodeStream"
	// SandboxMkdirProcedure is the fully-qualified name of the Sandbox's Mkdir RPC.
	SandboxMkdirProcedure = "/sandbox.v1.Sandbox/Mkdir"
	// SandboxRemoveProcedure is the fully-qualified name of the Sandbox's Remove RPC.
	SandboxRemoveProcedure = "/sandbox.v1.Sandbox/Remove"
	// SandboxUploadProcedure is the fully-qualified name of the Sandbox's Upload RPC.
	SandboxUploadProcedure = "/sandbox.v1.Sandbox/Upload"
)

// SandboxClient is a client for the sandbox.v1.Sandbox service.
type SandboxClient interface {
	// Exec runs a command and streams its IO. The client sends one ExecRequest
	// with the open oneof (cmd, env, cwd, pty), then zero or more ExecRequest with
	// the stdin oneof to feed stdin and resize oneof to resize a PTY. The server
	// streams stdout/stderr chunks and a terminal exit. This replaces both the
	// one-shot POST /v1/exec and the streaming POST /v1/exec/stream and the PTY
	// WebSocket GET /v1/pty: a non-PTY Exec is a streaming exec, a PTY Exec
	// (open.pty set) is the interactive terminal, both over the one bidi stream.
	Exec(context.Context) *connect.BidiStreamForClient[v1.ExecRequest, v1.ExecResponse]
	// ExecStream runs a non-interactive command and streams its output over a
	// server-streaming RPC. It is the HTTP/1.1-reachable counterpart to the bidi
	// Exec: Connect serves bidi only over HTTP/2, which HTTP/1.1-only clients
	// (httpx, the light SDKs) cannot reach against the cleartext standalone
	// server, whereas server-streaming works over HTTP/1.1 chunked transfer. The
	// request carries the same shape as ExecOpen but WITHOUT pty and WITHOUT
	// stdin, so this is non-interactive only; the bidi Exec stays for the
	// interactive and PTY cases. The reply reuses ExecResponse (stdout/stderr
	// chunks then a terminal exit).
	ExecStream(context.Context, *connect.Request[v1.ExecStreamRequest]) (*connect.ServerStreamForClient[v1.ExecResponse], error)
	// ReadFile streams the bytes of one file. Replaces POST /v1/files/read.
	ReadFile(context.Context, *connect.Request[v1.ReadFileRequest]) (*connect.ServerStreamForClient[v1.Chunk], error)
	// WriteFile streams bytes into one file. The first WriteFileRequest carries
	// the path and mode; subsequent messages carry content chunks. Replaces
	// POST /v1/files/write.
	WriteFile(context.Context) *connect.ClientStreamForClient[v1.WriteFileRequest, v1.WriteFileResult]
	// List enumerates a directory with AIP-158 pagination and filtering. Replaces
	// POST /v1/files/list.
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// Stat returns metadata for one path without reading its contents.
	Stat(context.Context, *connect.Request[v1.StatRequest]) (*connect.Response[v1.FileInfo], error)
	// Archive tars a subtree and streams the tar bytes (download), or, when
	// direction is UNTAR, accepts a tar to extract. Replaces the vsock tar_dir /
	// untar_dir workspace-transfer path. For UNTAR the client uses the streaming
	// WriteFile-style upload via ArchiveUploadRequest (see PortForward note: this
	// download-only RPC keeps the common path simple; the symmetric upload is a
	// follow-up streaming RPC, see docs/api/runtime-protocol.md).
	Archive(context.Context, *connect.Request[v1.ArchiveRequest]) (*connect.ServerStreamForClient[v1.Chunk], error)
	// Watch streams filesystem change events for a subtree until the client
	// cancels. New surface in v2 (no current HTTP/vsock equivalent).
	Watch(context.Context, *connect.Request[v1.WatchRequest]) (*connect.ServerStreamForClient[v1.FsEvent], error)
	// Processes lists the guest process table. New surface in v2.
	Processes(context.Context, *connect.Request[v1.ProcessesRequest]) (*connect.Response[v1.ProcessList], error)
	// Signal delivers a POSIX signal to a process in the guest. me.exit() is a
	// SIGTERM to the caller's own init (pid 1) and is the ONLY way a sandbox ends
	// itself. New surface in v2.
	Signal(context.Context, *connect.Request[v1.SignalRequest]) (*connect.Response[v1.SignalResponse], error)
	// PortForward proxies a guest TCP port over a bidirectional byte stream. Each
	// Frame carries a slice of one direction's bytes. New surface in v2.
	PortForward(context.Context) *connect.BidiStreamForClient[v1.Frame, v1.Frame]
	// Fork forks N sibling sandboxes from this live sandbox. Returns a
	// long-running Operation handle the caller polls; the controller materializes
	// the N siblings declaratively. Budget-gated by the fork allowance.
	Fork(context.Context, *connect.Request[v1.ForkRequest]) (*connect.Response[v1.Operation], error)
	// Checkpoint captures this sandbox's live state as a workspace Revision.
	// Returns the Revision handle. Budget-gated by the checkpoint allowance.
	Checkpoint(context.Context, *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.Revision], error)
	// ExtendLifetime extends this sandbox's lease. Returns the new Lease.
	// Budget-gated by the lifetime allowance.
	ExtendLifetime(context.Context, *connect.Request[v1.ExtendRequest]) (*connect.Response[v1.Lease], error)
	// Budget reports the caller's remaining self-service allowances.
	Budget(context.Context, *connect.Request[v1.BudgetRequest]) (*connect.Response[v1.BudgetStatus], error)
	// Vitals streams guest health samples (cpu steal, memory vs balloon, process
	// count) until the client cancels. New surface in v2.
	Vitals(context.Context, *connect.Request[v1.VitalsRequest]) (*connect.ServerStreamForClient[v1.GuestVitals], error)
	// RunCode runs a snippet of code in the sandbox kernel (default Python) and
	// streams back stdout, stderr, rich display results, and an exit code. The
	// first RunCodeRequest MUST carry `open`; subsequent messages may carry
	// `stdin` to feed interactive prompts.
	RunCode(context.Context) *connect.BidiStreamForClient[v1.RunCodeRequest, v1.RunCodeResponse]
	// RunCodeStream runs a code snippet and streams its output over a
	// server-streaming RPC. It is the HTTP/1.1-reachable counterpart to the bidi
	// RunCode (same rationale as ExecStream: bidi needs HTTP/2). The request
	// carries the RunCodeOpen shape WITHOUT stdin, so this is non-interactive
	// only; the bidi RunCode stays for the interactive case. The reply reuses
	// RunCodeResponse (stdout/stderr, rich result, kernel error, then exit_code).
	RunCodeStream(context.Context, *connect.Request[v1.RunCodeStreamRequest]) (*connect.ServerStreamForClient[v1.RunCodeResponse], error)
	// Mkdir creates a directory (and parents) at the given path.
	Mkdir(context.Context, *connect.Request[v1.MkdirRequest]) (*connect.Response[v1.MkdirResponse], error)
	// Remove deletes a file or directory. Set recursive to remove a non-empty
	// directory tree.
	Remove(context.Context, *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error)
	// Upload accepts a tar archive over a streaming request and extracts it at
	// the destination directory. The first UploadRequest MUST carry `open`;
	// subsequent messages carry raw tar bytes as `chunk`.
	Upload(context.Context) *connect.ClientStreamForClient[v1.UploadRequest, v1.UploadResult]
}

// NewSandboxClient constructs a client for the sandbox.v1.Sandbox service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSandboxClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SandboxClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sandboxMethods := v1.File_proto_sandbox_v1_sandbox_proto.Services().ByName("Sandbox").Methods()
	return &sandboxClient{
		exec: connect.NewClient[v1.ExecRequest, v1.ExecResponse](
			httpClient,
			baseURL+SandboxExecProcedure,
			connect.WithSchema(sandboxMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		execStream: connect.NewClient[v1.ExecStreamRequest, v1.ExecResponse](
			httpClient,
			baseURL+SandboxExecStreamProcedure,
			connect.WithSchema(sandboxMethods.ByName("ExecStream")),
			connect.WithClientOptions(opts...),
		),
		readFile: connect.NewClient[v1.ReadFileRequest, v1.Chunk](
			httpClient,
			baseURL+SandboxReadFileProcedure,
			connect.WithSchema(sandboxMethods.ByName("ReadFile")),
			connect.WithClientOptions(opts...),
		),
		writeFile: connect.NewClient[v1.WriteFileRequest, v1.WriteFileResult](
			httpClient,
			baseURL+SandboxWriteFileProcedure,
			connect.WithSchema(sandboxMethods.ByName("WriteFile")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+SandboxListProcedure,
			connect.WithSchema(sandboxMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		stat: connect.NewClient[v1.StatRequest, v1.FileInfo](
			httpClient,
			baseURL+SandboxStatProcedure,
			connect.WithSchema(sandboxMethods.ByName("Stat")),
			connect.WithClientOptions(opts...),
		),
		archive: connect.NewClient[v1.ArchiveRequest, v1.Chunk](
			httpClient,
			baseURL+SandboxArchiveProcedure,
			connect.WithSchema(sandboxMethods.ByName("Archive")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.WatchRequest, v1.FsEvent](
			httpClient,
			baseURL+SandboxWatchProcedure,
			connect.WithSchema(sandboxMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
		processes: connect.NewClient[v1.ProcessesRequest, v1.ProcessList](
			httpClient,
			baseURL+SandboxProcessesProcedure,
			connect.WithSchema(sandboxMethods.ByName("Processes")),
			connect.WithClientOptions(opts...),
		),
		signal: connect.NewClient[v1.SignalRequest, v1.SignalResponse](
			httpClient,
			baseURL+SandboxSignalProcedure,
			connect.WithSchema(sandboxMethods.ByName("Signal")),
			connect.WithClientOptions(opts...),
		),
		portForward: connect.NewClient[v1.Frame, v1.Frame](
			httpClient,
			baseURL+SandboxPortForwardProcedure,
			connect.WithSchema(sandboxMethods.ByName("PortForward")),
			connect.WithClientOptions(opts...),
		),
		fork: connect.NewClient[v1.ForkRequest, v1.Operation](
			httpClient,
			baseURL+SandboxForkProcedure,
			connect.WithSchema(sandboxMethods.ByName("Fork")),
			connect.WithClientOptions(opts...),
		),
		checkpoint: connect.NewClient[v1.CheckpointRequest, v1.Revision](
			httpClient,
			baseURL+SandboxCheckpointProcedure,
			connect.WithSchema(sandboxMethods.ByName("Checkpoint")),
			connect.WithClientOptions(opts...),
		),
		extendLifetime: connect.NewClient[v1.ExtendRequest, v1.Lease](
			httpClient,
			baseURL+SandboxExtendLifetimeProcedure,
			connect.WithSchema(sandboxMethods.ByName("ExtendLifetime")),
			connect.WithClientOptions(opts...),
		),
		budget: connect.NewClient[v1.BudgetRequest, v1.BudgetStatus](
			httpClient,
			baseURL+SandboxBudgetProcedure,
			connect.WithSchema(sandboxMethods.ByName("Budget")),
			connect.WithClientOptions(opts...),
		),
		vitals: connect.NewClient[v1.VitalsRequest, v1.GuestVitals](
			httpClient,
			baseURL+SandboxVitalsProcedure,
			connect.WithSchema(sandboxMethods.ByName("Vitals")),
			connect.WithClientOptions(opts...),
		),
		runCode: connect.NewClient[v1.RunCodeRequest, v1.RunCodeResponse](
			httpClient,
			baseURL+SandboxRunCodeProcedure,
			connect.WithSchema(sandboxMethods.ByName("RunCode")),
			connect.WithClientOptions(opts...),
		),
		runCodeStream: connect.NewClient[v1.RunCodeStreamRequest, v1.RunCodeResponse](
			httpClient,
			baseURL+SandboxRunCodeStreamProcedure,
			connect.WithSchema(sandboxMethods.ByName("RunCodeStream")),
			connect.WithClientOptions(opts...),
		),
		mkdir: connect.NewClient[v1.MkdirRequest, v1.MkdirResponse](
			httpClient,
			baseURL+SandboxMkdirProcedure,
			connect.WithSchema(sandboxMethods.ByName("Mkdir")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[v1.RemoveRequest, v1.RemoveResponse](
			httpClient,
			baseURL+SandboxRemoveProcedure,
			connect.WithSchema(sandboxMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
		upload: connect.NewClient[v1.UploadRequest, v1.UploadResult](
			httpClient,
			baseURL+SandboxUploadProcedure,
			connect.WithSchema(sandboxMethods.ByName("Upload")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sandboxClient implements SandboxClient.
type sandboxClient struct {
	exec           *connect.Client[v1.ExecRequest, v1.ExecResponse]
	execStream     *connect.Client[v1.ExecStreamRequest, v1.ExecResponse]
	readFile       *connect.Client[v1.ReadFileRequest, v1.Chunk]
	writeFile      *connect.Client[v1.WriteFileRequest, v1.WriteFileResult]
	list           *connect.Client[v1.ListRequest, v1.ListResponse]
	stat           *connect.Client[v1.StatRequest, v1.FileInfo]
	archive        *connect.Client[v1.ArchiveRequest, v1.Chunk]
	watch          *connect.Client[v1.WatchRequest, v1.FsEvent]
	processes      *connect.Client[v1.ProcessesRequest, v1.ProcessList]
	signal         *connect.Client[v1.SignalRequest, v1.SignalResponse]
	portForward    *connect.Client[v1.Frame, v1.Frame]
	fork           *connect.Client[v1.ForkRequest, v1.Operation]
	checkpoint     *connect.Client[v1.CheckpointRequest, v1.Revision]
	extendLifetime *connect.Client[v1.ExtendRequest, v1.Lease]
	budget         *connect.Client[v1.BudgetRequest, v1.BudgetStatus]
	vitals         *connect.Client[v1.VitalsRequest, v1.GuestVitals]
	runCode        *connect.Client[v1.RunCodeRequest, v1.RunCodeResponse]
	runCodeStream  *connect.Client[v1.RunCodeStreamRequest, v1.RunCodeResponse]
	mkdir          *connect.Client[v1.MkdirRequest, v1.MkdirResponse]
	remove         *connect.Client[v1.RemoveRequest, v1.RemoveResponse]
	upload         *connect.Client[v1.UploadRequest, v1.UploadResult]
}

// Exec calls sandbox.v1.Sandbox.Exec.
func (c *sandboxClient) Exec(ctx context.Context) *connect.BidiStreamForClient[v1.ExecRequest, v1.ExecResponse] {
	return c.exec.CallBidiStream(ctx)
}

// ExecStream calls sandbox.v1.Sandbox.ExecStream.
func (c *sandboxClient) ExecStream(ctx context.Context, req *connect.Request[v1.ExecStreamRequest]) (*connect.ServerStreamForClient[v1.ExecResponse], error) {
	return c.execStream.CallServerStream(ctx, req)
}

// ReadFile calls sandbox.v1.Sandbox.ReadFile.
func (c *sandboxClient) ReadFile(ctx context.Context, req *connect.Request[v1.ReadFileRequest]) (*connect.ServerStreamForClient[v1.Chunk], error) {
	return c.readFile.CallServerStream(ctx, req)
}

// WriteFile calls sandbox.v1.Sandbox.WriteFile.
func (c *sandboxClient) WriteFile(ctx context.Context) *connect.ClientStreamForClient[v1.WriteFileRequest, v1.WriteFileResult] {
	return c.writeFile.CallClientStream(ctx)
}

// List calls sandbox.v1.Sandbox.List.
func (c *sandboxClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Stat calls sandbox.v1.Sandbox.Stat.
func (c *sandboxClient) Stat(ctx context.Context, req *connect.Request[v1.StatRequest]) (*connect.Response[v1.FileInfo], error) {
	return c.stat.CallUnary(ctx, req)
}

// Archive calls sandbox.v1.Sandbox.Archive.
func (c *sandboxClient) Archive(ctx context.Context, req *connect.Request[v1.ArchiveRequest]) (*connect.ServerStreamForClient[v1.Chunk], error) {
	return c.archive.CallServerStream(ctx, req)
}

// Watch calls sandbox.v1.Sandbox.Watch.
func (c *sandboxClient) Watch(ctx context.Context, req *connect.Request[v1.WatchRequest]) (*connect.ServerStreamForClient[v1.FsEvent], error) {
	return c.watch.CallServerStream(ctx, req)
}

// Processes calls sandbox.v1.Sandbox.Processes.
func (c *sandboxClient) Processes(ctx context.Context, req *connect.Request[v1.ProcessesRequest]) (*connect.Response[v1.ProcessList], error) {
	return c.processes.CallUnary(ctx, req)
}

// Signal calls sandbox.v1.Sandbox.Signal.
func (c *sandboxClient) Signal(ctx context.Context, req *connect.Request[v1.SignalRequest]) (*connect.Response[v1.SignalResponse], error) {
	return c.signal.CallUnary(ctx, req)
}

// PortForward calls sandbox.v1.Sandbox.PortForward.
func (c *sandboxClient) PortForward(ctx context.Context) *connect.BidiStreamForClient[v1.Frame, v1.Frame] {
	return c.portForward.CallBidiStream(ctx)
}

// Fork calls sandbox.v1.Sandbox.Fork.
func (c *sandboxClient) Fork(ctx context.Context, req *connect.Request[v1.ForkRequest]) (*connect.Response[v1.Operation], error) {
	return c.fork.CallUnary(ctx, req)
}

// Checkpoint calls sandbox.v1.Sandbox.Checkpoint.
func (c *sandboxClient) Checkpoint(ctx context.Context, req *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.Revision], error) {
	return c.checkpoint.CallUnary(ctx, req)
}

// ExtendLifetime calls sandbox.v1.Sandbox.ExtendLifetime.
func (c *sandboxClient) ExtendLifetime(ctx context.Context, req *connect.Request[v1.ExtendRequest]) (*connect.Response[v1.Lease], error) {
	return c.extendLifetime.CallUnary(ctx, req)
}

// Budget calls sandbox.v1.Sandbox.Budget.
func (c *sandboxClient) Budget(ctx context.Context, req *connect.Request[v1.BudgetRequest]) (*connect.Response[v1.BudgetStatus], error) {
	return c.budget.CallUnary(ctx, req)
}

// Vitals calls sandbox.v1.Sandbox.Vitals.
func (c *sandboxClient) Vitals(ctx context.Context, req *connect.Request[v1.VitalsRequest]) (*connect.ServerStreamForClient[v1.GuestVitals], error) {
	return c.vitals.CallServerStream(ctx, req)
}

// RunCode calls sandbox.v1.Sandbox.RunCode.
func (c *sandboxClient) RunCode(ctx context.Context) *connect.BidiStreamForClient[v1.RunCodeRequest, v1.RunCodeResponse] {
	return c.runCode.CallBidiStream(ctx)
}

// RunCodeStream calls sandbox.v1.Sandbox.RunCodeStream.
func (c *sandboxClient) RunCodeStream(ctx context.Context, req *connect.Request[v1.RunCodeStreamRequest]) (*connect.ServerStreamForClient[v1.RunCodeResponse], error) {
	return c.runCodeStream.CallServerStream(ctx, req)
}

// Mkdir calls sandbox.v1.Sandbox.Mkdir.
func (c *sandboxClient) Mkdir(ctx context.Context, req *connect.Request[v1.MkdirRequest]) (*connect.Response[v1.MkdirResponse], error) {
	return c.mkdir.CallUnary(ctx, req)
}

// Remove calls sandbox.v1.Sandbox.Remove.
func (c *sandboxClient) Remove(ctx context.Context, req *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error) {
	return c.remove.CallUnary(ctx, req)
}

// Upload calls sandbox.v1.Sandbox.Upload.
func (c *sandboxClient) Upload(ctx context.Context) *connect.ClientStreamForClient[v1.UploadRequest, v1.UploadResult] {
	return c.upload.CallClientStream(ctx)
}

// SandboxHandler is an implementation of the sandbox.v1.Sandbox service.
type SandboxHandler interface {
	// Exec runs a command and streams its IO. The client sends one ExecRequest
	// with the open oneof (cmd, env, cwd, pty), then zero or more ExecRequest with
	// the stdin oneof to feed stdin and resize oneof to resize a PTY. The server
	// streams stdout/stderr chunks and a terminal exit. This replaces both the
	// one-shot POST /v1/exec and the streaming POST /v1/exec/stream and the PTY
	// WebSocket GET /v1/pty: a non-PTY Exec is a streaming exec, a PTY Exec
	// (open.pty set) is the interactive terminal, both over the one bidi stream.
	Exec(context.Context, *connect.BidiStream[v1.ExecRequest, v1.ExecResponse]) error
	// ExecStream runs a non-interactive command and streams its output over a
	// server-streaming RPC. It is the HTTP/1.1-reachable counterpart to the bidi
	// Exec: Connect serves bidi only over HTTP/2, which HTTP/1.1-only clients
	// (httpx, the light SDKs) cannot reach against the cleartext standalone
	// server, whereas server-streaming works over HTTP/1.1 chunked transfer. The
	// request carries the same shape as ExecOpen but WITHOUT pty and WITHOUT
	// stdin, so this is non-interactive only; the bidi Exec stays for the
	// interactive and PTY cases. The reply reuses ExecResponse (stdout/stderr
	// chunks then a terminal exit).
	ExecStream(context.Context, *connect.Request[v1.ExecStreamRequest], *connect.ServerStream[v1.ExecResponse]) error
	// ReadFile streams the bytes of one file. Replaces POST /v1/files/read.
	ReadFile(context.Context, *connect.Request[v1.ReadFileRequest], *connect.ServerStream[v1.Chunk]) error
	// WriteFile streams bytes into one file. The first WriteFileRequest carries
	// the path and mode; subsequent messages carry content chunks. Replaces
	// POST /v1/files/write.
	WriteFile(context.Context, *connect.ClientStream[v1.WriteFileRequest]) (*connect.Response[v1.WriteFileResult], error)
	// List enumerates a directory with AIP-158 pagination and filtering. Replaces
	// POST /v1/files/list.
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// Stat returns metadata for one path without reading its contents.
	Stat(context.Context, *connect.Request[v1.StatRequest]) (*connect.Response[v1.FileInfo], error)
	// Archive tars a subtree and streams the tar bytes (download), or, when
	// direction is UNTAR, accepts a tar to extract. Replaces the vsock tar_dir /
	// untar_dir workspace-transfer path. For UNTAR the client uses the streaming
	// WriteFile-style upload via ArchiveUploadRequest (see PortForward note: this
	// download-only RPC keeps the common path simple; the symmetric upload is a
	// follow-up streaming RPC, see docs/api/runtime-protocol.md).
	Archive(context.Context, *connect.Request[v1.ArchiveRequest], *connect.ServerStream[v1.Chunk]) error
	// Watch streams filesystem change events for a subtree until the client
	// cancels. New surface in v2 (no current HTTP/vsock equivalent).
	Watch(context.Context, *connect.Request[v1.WatchRequest], *connect.ServerStream[v1.FsEvent]) error
	// Processes lists the guest process table. New surface in v2.
	Processes(context.Context, *connect.Request[v1.ProcessesRequest]) (*connect.Response[v1.ProcessList], error)
	// Signal delivers a POSIX signal to a process in the guest. me.exit() is a
	// SIGTERM to the caller's own init (pid 1) and is the ONLY way a sandbox ends
	// itself. New surface in v2.
	Signal(context.Context, *connect.Request[v1.SignalRequest]) (*connect.Response[v1.SignalResponse], error)
	// PortForward proxies a guest TCP port over a bidirectional byte stream. Each
	// Frame carries a slice of one direction's bytes. New surface in v2.
	PortForward(context.Context, *connect.BidiStream[v1.Frame, v1.Frame]) error
	// Fork forks N sibling sandboxes from this live sandbox. Returns a
	// long-running Operation handle the caller polls; the controller materializes
	// the N siblings declaratively. Budget-gated by the fork allowance.
	Fork(context.Context, *connect.Request[v1.ForkRequest]) (*connect.Response[v1.Operation], error)
	// Checkpoint captures this sandbox's live state as a workspace Revision.
	// Returns the Revision handle. Budget-gated by the checkpoint allowance.
	Checkpoint(context.Context, *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.Revision], error)
	// ExtendLifetime extends this sandbox's lease. Returns the new Lease.
	// Budget-gated by the lifetime allowance.
	ExtendLifetime(context.Context, *connect.Request[v1.ExtendRequest]) (*connect.Response[v1.Lease], error)
	// Budget reports the caller's remaining self-service allowances.
	Budget(context.Context, *connect.Request[v1.BudgetRequest]) (*connect.Response[v1.BudgetStatus], error)
	// Vitals streams guest health samples (cpu steal, memory vs balloon, process
	// count) until the client cancels. New surface in v2.
	Vitals(context.Context, *connect.Request[v1.VitalsRequest], *connect.ServerStream[v1.GuestVitals]) error
	// RunCode runs a snippet of code in the sandbox kernel (default Python) and
	// streams back stdout, stderr, rich display results, and an exit code. The
	// first RunCodeRequest MUST carry `open`; subsequent messages may carry
	// `stdin` to feed interactive prompts.
	RunCode(context.Context, *connect.BidiStream[v1.RunCodeRequest, v1.RunCodeResponse]) error
	// RunCodeStream runs a code snippet and streams its output over a
	// server-streaming RPC. It is the HTTP/1.1-reachable counterpart to the bidi
	// RunCode (same rationale as ExecStream: bidi needs HTTP/2). The request
	// carries the RunCodeOpen shape WITHOUT stdin, so this is non-interactive
	// only; the bidi RunCode stays for the interactive case. The reply reuses
	// RunCodeResponse (stdout/stderr, rich result, kernel error, then exit_code).
	RunCodeStream(context.Context, *connect.Request[v1.RunCodeStreamRequest], *connect.ServerStream[v1.RunCodeResponse]) error
	// Mkdir creates a directory (and parents) at the given path.
	Mkdir(context.Context, *connect.Request[v1.MkdirRequest]) (*connect.Response[v1.MkdirResponse], error)
	// Remove deletes a file or directory. Set recursive to remove a non-empty
	// directory tree.
	Remove(context.Context, *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error)
	// Upload accepts a tar archive over a streaming request and extracts it at
	// the destination directory. The first UploadRequest MUST carry `open`;
	// subsequent messages carry raw tar bytes as `chunk`.
	Upload(context.Context, *connect.ClientStream[v1.UploadRequest]) (*connect.Response[v1.UploadResult], error)
}

// NewSandboxHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSandboxHandler(svc SandboxHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sandboxMethods := v1.File_proto_sandbox_v1_sandbox_proto.Services().ByName("Sandbox").Methods()
	sandboxExecHandler := connect.NewBidiStreamHandler(
		SandboxExecProcedure,
		svc.Exec,
		connect.WithSchema(sandboxMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxExecStreamHandler := connect.NewServerStreamHandler(
		SandboxExecStreamProcedure,
		svc.ExecStream,
		connect.WithSchema(sandboxMethods.ByName("ExecStream")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxReadFileHandler := connect.NewServerStreamHandler(
		SandboxReadFileProcedure,
		svc.ReadFile,
		connect.WithSchema(sandboxMethods.ByName("ReadFile")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxWriteFileHandler := connect.NewClientStreamHandler(
		SandboxWriteFileProcedure,
		svc.WriteFile,
		connect.WithSchema(sandboxMethods.ByName("WriteFile")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxListHandler := connect.NewUnaryHandler(
		SandboxListProcedure,
		svc.List,
		connect.WithSchema(sandboxMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxStatHandler := connect.NewUnaryHandler(
		SandboxStatProcedure,
		svc.Stat,
		connect.WithSchema(sandboxMethods.ByName("Stat")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxArchiveHandler := connect.NewServerStreamHandler(
		SandboxArchiveProcedure,
		svc.Archive,
		connect.WithSchema(sandboxMethods.ByName("Archive")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxWatchHandler := connect.NewServerStreamHandler(
		SandboxWatchProcedure,
		svc.Watch,
		connect.WithSchema(sandboxMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxProcessesHandler := connect.NewUnaryHandler(
		SandboxProcessesProcedure,
		svc.Processes,
		connect.WithSchema(sandboxMethods.ByName("Processes")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxSignalHandler := connect.NewUnaryHandler(
		SandboxSignalProcedure,
		svc.Signal,
		connect.WithSchema(sandboxMethods.ByName("Signal")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxPortForwardHandler := connect.NewBidiStreamHandler(
		SandboxPortForwardProcedure,
		svc.PortForward,
		connect.WithSchema(sandboxMethods.ByName("PortForward")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxForkHandler := connect.NewUnaryHandler(
		SandboxForkProcedure,
		svc.Fork,
		connect.WithSchema(sandboxMethods.ByName("Fork")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxCheckpointHandler := connect.NewUnaryHandler(
		SandboxCheckpointProcedure,
		svc.Checkpoint,
		connect.WithSchema(sandboxMethods.ByName("Checkpoint")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxExtendLifetimeHandler := connect.NewUnaryHandler(
		SandboxExtendLifetimeProcedure,
		svc.ExtendLifetime,
		connect.WithSchema(sandboxMethods.ByName("ExtendLifetime")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxBudgetHandler := connect.NewUnaryHandler(
		SandboxBudgetProcedure,
		svc.Budget,
		connect.WithSchema(sandboxMethods.ByName("Budget")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxVitalsHandler := connect.NewServerStreamHandler(
		SandboxVitalsProcedure,
		svc.Vitals,
		connect.WithSchema(sandboxMethods.ByName("Vitals")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxRunCodeHandler := connect.NewBidiStreamHandler(
		SandboxRunCodeProcedure,
		svc.RunCode,
		connect.WithSchema(sandboxMethods.ByName("RunCode")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxRunCodeStreamHandler := connect.NewServerStreamHandler(
		SandboxRunCodeStreamProcedure,
		svc.RunCodeStream,
		connect.WithSchema(sandboxMethods.ByName("RunCodeStream")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxMkdirHandler := connect.NewUnaryHandler(
		SandboxMkdirProcedure,
		svc.Mkdir,
		connect.WithSchema(sandboxMethods.ByName("Mkdir")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxRemoveHandler := connect.NewUnaryHandler(
		SandboxRemoveProcedure,
		svc.Remove,
		connect.WithSchema(sandboxMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxUploadHandler := connect.NewClientStreamHandler(
		SandboxUploadProcedure,
		svc.Upload,
		connect.WithSchema(sandboxMethods.ByName("Upload")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sandbox.v1.Sandbox/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SandboxExecProcedure:
			sandboxExecHandler.ServeHTTP(w, r)
		case SandboxExecStreamProcedure:
			sandboxExecStreamHandler.ServeHTTP(w, r)
		case SandboxReadFileProcedure:
			sandboxReadFileHandler.ServeHTTP(w, r)
		case SandboxWriteFileProcedure:
			sandboxWriteFileHandler.ServeHTTP(w, r)
		case SandboxListProcedure:
			sandboxListHandler.ServeHTTP(w, r)
		case SandboxStatProcedure:
			sandboxStatHandler.ServeHTTP(w, r)
		case SandboxArchiveProcedure:
			sandboxArchiveHandler.ServeHTTP(w, r)
		case SandboxWatchProcedure:
			sandboxWatchHandler.ServeHTTP(w, r)
		case SandboxProcessesProcedure:
			sandboxProcessesHandler.ServeHTTP(w, r)
		case SandboxSignalProcedure:
			sandboxSignalHandler.ServeHTTP(w, r)
		case SandboxPortForwardProcedure:
			sandboxPortForwardHandler.ServeHTTP(w, r)
		case SandboxForkProcedure:
			sandboxForkHandler.ServeHTTP(w, r)
		case SandboxCheckpointProcedure:
			sandboxCheckpointHandler.ServeHTTP(w, r)
		case SandboxExtendLifetimeProcedure:
			sandboxExtendLifetimeHandler.ServeHTTP(w, r)
		case SandboxBudgetProcedure:
			sandboxBudgetHandler.ServeHTTP(w, r)
		case SandboxVitalsProcedure:
			sandboxVitalsHandler.ServeHTTP(w, r)
		case SandboxRunCodeProcedure:
			sandboxRunCodeHandler.ServeHTTP(w, r)
		case SandboxRunCodeStreamProcedure:
			sandboxRunCodeStreamHandler.ServeHTTP(w, r)
		case SandboxMkdirProcedure:
			sandboxMkdirHandler.ServeHTTP(w, r)
		case SandboxRemoveProcedure:
			sandboxRemoveHandler.ServeHTTP(w, r)
		case SandboxUploadProcedure:
			sandboxUploadHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSandboxHandler returns CodeUnimplemented from all methods.
type UnimplementedSandboxHandler struct{}

func (UnimplementedSandboxHandler) Exec(context.Context, *connect.BidiStream[v1.ExecRequest, v1.ExecResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Exec is not implemented"))
}

func (UnimplementedSandboxHandler) ExecStream(context.Context, *connect.Request[v1.ExecStreamRequest], *connect.ServerStream[v1.ExecResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.ExecStream is not implemented"))
}

func (UnimplementedSandboxHandler) ReadFile(context.Context, *connect.Request[v1.ReadFileRequest], *connect.ServerStream[v1.Chunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.ReadFile is not implemented"))
}

func (UnimplementedSandboxHandler) WriteFile(context.Context, *connect.ClientStream[v1.WriteFileRequest]) (*connect.Response[v1.WriteFileResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.WriteFile is not implemented"))
}

func (UnimplementedSandboxHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.List is not implemented"))
}

func (UnimplementedSandboxHandler) Stat(context.Context, *connect.Request[v1.StatRequest]) (*connect.Response[v1.FileInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Stat is not implemented"))
}

func (UnimplementedSandboxHandler) Archive(context.Context, *connect.Request[v1.ArchiveRequest], *connect.ServerStream[v1.Chunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Archive is not implemented"))
}

func (UnimplementedSandboxHandler) Watch(context.Context, *connect.Request[v1.WatchRequest], *connect.ServerStream[v1.FsEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Watch is not implemented"))
}

func (UnimplementedSandboxHandler) Processes(context.Context, *connect.Request[v1.ProcessesRequest]) (*connect.Response[v1.ProcessList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Processes is not implemented"))
}

func (UnimplementedSandboxHandler) Signal(context.Context, *connect.Request[v1.SignalRequest]) (*connect.Response[v1.SignalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Signal is not implemented"))
}

func (UnimplementedSandboxHandler) PortForward(context.Context, *connect.BidiStream[v1.Frame, v1.Frame]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.PortForward is not implemented"))
}

func (UnimplementedSandboxHandler) Fork(context.Context, *connect.Request[v1.ForkRequest]) (*connect.Response[v1.Operation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Fork is not implemented"))
}

func (UnimplementedSandboxHandler) Checkpoint(context.Context, *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.Revision], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Checkpoint is not implemented"))
}

func (UnimplementedSandboxHandler) ExtendLifetime(context.Context, *connect.Request[v1.ExtendRequest]) (*connect.Response[v1.Lease], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.ExtendLifetime is not implemented"))
}

func (UnimplementedSandboxHandler) Budget(context.Context, *connect.Request[v1.BudgetRequest]) (*connect.Response[v1.BudgetStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Budget is not implemented"))
}

func (UnimplementedSandboxHandler) Vitals(context.Context, *connect.Request[v1.VitalsRequest], *connect.ServerStream[v1.GuestVitals]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Vitals is not implemented"))
}

func (UnimplementedSandboxHandler) RunCode(context.Context, *connect.BidiStream[v1.RunCodeRequest, v1.RunCodeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.RunCode is not implemented"))
}

func (UnimplementedSandboxHandler) RunCodeStream(context.Context, *connect.Request[v1.RunCodeStreamRequest], *connect.ServerStream[v1.RunCodeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.RunCodeStream is not implemented"))
}

func (UnimplementedSandboxHandler) Mkdir(context.Context, *connect.Request[v1.MkdirRequest]) (*connect.Response[v1.MkdirResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Mkdir is not implemented"))
}

func (UnimplementedSandboxHandler) Remove(context.Context, *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Remove is not implemented"))
}

func (UnimplementedSandboxHandler) Upload(context.Context, *connect.ClientStream[v1.UploadRequest]) (*connect.Response[v1.UploadResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.v1.Sandbox.Upload is not implemented"))
}
