// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/sandbox/controlv1/internal.proto

// Internal host-to-guest control service (sandbox.internal.v1).
//
// This service carries secrets and the fork-correctness handshake. It is served
// by the guest agent on a DISTINCT vsock service port from the public Sandbox
// service. It is NEVER part of sandbox.v1.Sandbox, NEVER exposed on forkd :9091,
// and NEVER reachable from tenant code. The host (forkd) is the only caller.
//
// All three RPCs may carry sensitive material:
//   - NotifyForked: Entropy is raw CRNG seed material; HostWallClockNanos can
//     leak host timing. Neither is ever logged by host or guest.
//   - Configure: Env and Secrets are claim-time secret values injected into the
//     guest process environment. Values are NEVER logged or echoed by either side.
//   - Ping: carries no secrets; used for health checks.
//
// Package is versioned independently of sandbox.v1 with a one-major-version
// compatibility window (docs/api/runtime-protocol.md). The service name
// "sandbox.internal.v1.Control" is the vsock service discriminator used by the
// guest to accept connections on its dedicated control port.
package sandboxinternalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	controlv1 "mitos.run/mitos/proto/sandbox/controlv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ControlName is the fully-qualified name of the Control service.
	ControlName = "sandbox.internal.v1.Control"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ControlNotifyForkedProcedure is the fully-qualified name of the Control's NotifyForked RPC.
	ControlNotifyForkedProcedure = "/sandbox.internal.v1.Control/NotifyForked"
	// ControlConfigureProcedure is the fully-qualified name of the Control's Configure RPC.
	ControlConfigureProcedure = "/sandbox.internal.v1.Control/Configure"
	// ControlPingProcedure is the fully-qualified name of the Control's Ping RPC.
	ControlPingProcedure = "/sandbox.internal.v1.Control/Ping"
)

// ControlClient is a client for the sandbox.internal.v1.Control service.
type ControlClient interface {
	// NotifyForked tells the guest that a snapshot restore just occurred. The
	// guest must: (1) reseed the kernel CRNG with Entropy, (2) step CLOCK_REALTIME
	// to HostWallClockNanos, (3) reconfigure eth0 when Network is present, and
	// (4) mount per-fork volumes when Volumes is non-empty. The response reports
	// what the guest actually applied so the host can record fork-correctness
	// observability without logging the raw sensitive fields.
	NotifyForked(context.Context, *connect.Request[controlv1.NotifyForkedRequest]) (*connect.Response[controlv1.NotifyForkedResponse], error)
	// Configure delivers claim-time environment variables and secrets to the guest
	// after restore. THIS RPC CARRIES SECRET VALUES. Neither side ever logs Env or
	// Secrets values; only key names and counts are safe to log. This RPC is
	// host-trusted and must never be exposed on any public surface.
	Configure(context.Context, *connect.Request[controlv1.ConfigureRequest]) (*connect.Response[controlv1.ConfigureResponse], error)
	// Ping checks that the guest agent is alive and returns its uptime. Carries no
	// secrets; safe to log.
	Ping(context.Context, *connect.Request[controlv1.PingRequest]) (*connect.Response[controlv1.PingResponse], error)
}

// NewControlClient constructs a client for the sandbox.internal.v1.Control service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControlClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControlClient {
	baseURL = strings.TrimRight(baseURL, "/")
	controlMethods := controlv1.File_proto_sandbox_controlv1_internal_proto.Services().ByName("Control").Methods()
	return &controlClient{
		notifyForked: connect.NewClient[controlv1.NotifyForkedRequest, controlv1.NotifyForkedResponse](
			httpClient,
			baseURL+ControlNotifyForkedProcedure,
			connect.WithSchema(controlMethods.ByName("NotifyForked")),
			connect.WithClientOptions(opts...),
		),
		configure: connect.NewClient[controlv1.ConfigureRequest, controlv1.ConfigureResponse](
			httpClient,
			baseURL+ControlConfigureProcedure,
			connect.WithSchema(controlMethods.ByName("Configure")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[controlv1.PingRequest, controlv1.PingResponse](
			httpClient,
			baseURL+ControlPingProcedure,
			connect.WithSchema(controlMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
	}
}

// controlClient implements ControlClient.
type controlClient struct {
	notifyForked *connect.Client[controlv1.NotifyForkedRequest, controlv1.NotifyForkedResponse]
	configure    *connect.Client[controlv1.ConfigureRequest, controlv1.ConfigureResponse]
	ping         *connect.Client[controlv1.PingRequest, controlv1.PingResponse]
}

// NotifyForked calls sandbox.internal.v1.Control.NotifyForked.
func (c *controlClient) NotifyForked(ctx context.Context, req *connect.Request[controlv1.NotifyForkedRequest]) (*connect.Response[controlv1.NotifyForkedResponse], error) {
	return c.notifyForked.CallUnary(ctx, req)
}

// Configure calls sandbox.internal.v1.Control.Configure.
func (c *controlClient) Configure(ctx context.Context, req *connect.Request[controlv1.ConfigureRequest]) (*connect.Response[controlv1.ConfigureResponse], error) {
	return c.configure.CallUnary(ctx, req)
}

// Ping calls sandbox.internal.v1.Control.Ping.
func (c *controlClient) Ping(ctx context.Context, req *connect.Request[controlv1.PingRequest]) (*connect.Response[controlv1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// ControlHandler is an implementation of the sandbox.internal.v1.Control service.
type ControlHandler interface {
	// NotifyForked tells the guest that a snapshot restore just occurred. The
	// guest must: (1) reseed the kernel CRNG with Entropy, (2) step CLOCK_REALTIME
	// to HostWallClockNanos, (3) reconfigure eth0 when Network is present, and
	// (4) mount per-fork volumes when Volumes is non-empty. The response reports
	// what the guest actually applied so the host can record fork-correctness
	// observability without logging the raw sensitive fields.
	NotifyForked(context.Context, *connect.Request[controlv1.NotifyForkedRequest]) (*connect.Response[controlv1.NotifyForkedResponse], error)
	// Configure delivers claim-time environment variables and secrets to the guest
	// after restore. THIS RPC CARRIES SECRET VALUES. Neither side ever logs Env or
	// Secrets values; only key names and counts are safe to log. This RPC is
	// host-trusted and must never be exposed on any public surface.
	Configure(context.Context, *connect.Request[controlv1.ConfigureRequest]) (*connect.Response[controlv1.ConfigureResponse], error)
	// Ping checks that the guest agent is alive and returns its uptime. Carries no
	// secrets; safe to log.
	Ping(context.Context, *connect.Request[controlv1.PingRequest]) (*connect.Response[controlv1.PingResponse], error)
}

// NewControlHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControlHandler(svc ControlHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controlMethods := controlv1.File_proto_sandbox_controlv1_internal_proto.Services().ByName("Control").Methods()
	controlNotifyForkedHandler := connect.NewUnaryHandler(
		ControlNotifyForkedProcedure,
		svc.NotifyForked,
		connect.WithSchema(controlMethods.ByName("NotifyForked")),
		connect.WithHandlerOptions(opts...),
	)
	controlConfigureHandler := connect.NewUnaryHandler(
		ControlConfigureProcedure,
		svc.Configure,
		connect.WithSchema(controlMethods.ByName("Configure")),
		connect.WithHandlerOptions(opts...),
	)
	controlPingHandler := connect.NewUnaryHandler(
		ControlPingProcedure,
		svc.Ping,
		connect.WithSchema(controlMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sandbox.internal.v1.Control/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControlNotifyForkedProcedure:
			controlNotifyForkedHandler.ServeHTTP(w, r)
		case ControlConfigureProcedure:
			controlConfigureHandler.ServeHTTP(w, r)
		case ControlPingProcedure:
			controlPingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControlHandler returns CodeUnimplemented from all methods.
type UnimplementedControlHandler struct{}

func (UnimplementedControlHandler) NotifyForked(context.Context, *connect.Request[controlv1.NotifyForkedRequest]) (*connect.Response[controlv1.NotifyForkedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.internal.v1.Control.NotifyForked is not implemented"))
}

func (UnimplementedControlHandler) Configure(context.Context, *connect.Request[controlv1.ConfigureRequest]) (*connect.Response[controlv1.ConfigureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.internal.v1.Control.Configure is not implemented"))
}

func (UnimplementedControlHandler) Ping(context.Context, *connect.Request[controlv1.PingRequest]) (*connect.Response[controlv1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandbox.internal.v1.Control.Ping is not implemented"))
}
